package me.notanullpointer.xc2editor.save;

import me.notanullpointer.xc2editor.assets.Image;

import java.util.ArrayList;

public enum Accessory {

    ABYSS_VEST_RARE(1, "Abyss Vest \u25C6\u25C6", "Boosts maximum HP by 24%.", Rarity.RARE, 2),
    GEAR_VEST_COMMON(2, "Gear Vest \u25C6", "Boosts maximum HP by 20%.", Rarity.COMMON, 2),
    JADE_VEST_COMMON(3, "Jade Vest \u25C6", "Boosts maximum HP by 25%.", Rarity.COMMON, 2),
    TITANIUM_VEST_COMMON(4, "Titanium Vest \u25C6", "Boosts maximum HP by 30%.", Rarity.COMMON, 2),
    STEAM_BELT_COMMON(5, "Steam Belt \u25C6", "Boosts Strength by 20%.", Rarity.COMMON, 4),
    SILVER_BELT_COMMON(6, "Silver Belt \u25C6", "Boosts Strength by 25%.", Rarity.COMMON, 4),
    CERAMIC_BELT_COMMON(7, "Ceramic Belt \u25C6", "Boosts Strength by 30%.", Rarity.COMMON, 4),
    BOLT_HAT_COMMON(8, "Bolt Hat \u25C6", "Boosts Ether by 20%.", Rarity.COMMON, 1),
    PEARL_HAT_COMMON(9, "Pearl Hat \u25C6", "Boosts Ether by 25%.", Rarity.COMMON, 1),
    FIBER_HAT_COMMON(10, "Fiber Hat \u25C6", "Boosts Ether by 30%.", Rarity.COMMON, 1),
    RAINBOW_GLOVES_COMMON(11, "Rainbow Gloves \u25C6", "Boosts Dexterity by 20%.", Rarity.COMMON, 6),
    HERO_GLOVES_COMMON(12, "Hero Gloves \u25C6", "Boosts Dexterity by 25%.", Rarity.COMMON, 6),
    CARBON_GLOVES_COMMON(13, "Carbon Gloves \u25C6", "Boosts Dexterity by 30%.", Rarity.COMMON, 6),
    SHELL_SHOES_COMMON(14, "Shell Shoes \u25C6", "Boosts Agility by 20%.", Rarity.COMMON, 0),
    ASSASSIN_SHOES_COMMON(15, "Assassin Shoes \u25C6", "Boosts Agility by 25%.", Rarity.COMMON, 0),
    ESTER_SHOES_COMMON(16, "Ester Shoes \u25C6", "Boosts Agility by 30%.", Rarity.COMMON, 0),
    NACRE_CHOKER_COMMON(17, "Nacre Choker \u25C6", "Boosts Luck by 20%.", Rarity.COMMON, 3),
    GODDESS_CHOKER_COMMON(18, "Goddess Choker \u25C6", "Boosts Luck by 25%.", Rarity.COMMON, 3),
    COMET_CHOKER_COMMON(19, "Comet Choker \u25C6", "Boosts Luck by 30%.", Rarity.COMMON, 3),
    RIGID_VEST_COMMON(20, "Rigid Vest \u25C6", "Increases maximum HP by 200.", Rarity.COMMON, 2),
    INFANTRY_VEST_COMMON(21, "Infantry Vest \u25C6", "Increases maximum HP by 400.", Rarity.COMMON, 2),
    MUSCLE_BELT_COMMON(22, "Muscle Belt \u25C6", "Increases Strength by 20.", Rarity.COMMON, 4),
    CHAMPION_BELT_COMMON(23, "Champion Belt \u25C6", "Increases Strength by 25.", Rarity.COMMON, 4),
    FLUFFY_HAT_COMMON(24, "Fluffy Hat \u25C6", "Increases Ether by 20.", Rarity.COMMON, 1),
    FABULOUS_HAT_COMMON(25, "Fabulous Hat \u25C6", "Increases Ether by 25.", Rarity.COMMON, 1),
    LEATHER_GLOVES_COMMON(26, "Leather Gloves \u25C6", "Increases Dexterity by 20.", Rarity.COMMON, 6),
    SMITHY_GLOVES_COMMON(27, "Smithy Gloves \u25C6", "Increases Dexterity by 25.", Rarity.COMMON, 6),
    WOLF_SHOES_COMMON(28, "Wolf Shoes \u25C6", "Increases Agility by 10.", Rarity.COMMON, 0),
    SPRING_SHOES_COMMON(29, "Spring Shoes \u25C6", "Increases Agility by 15.", Rarity.COMMON, 0),
    BUNNIT_CHOKER_COMMON(30, "Bunnit Choker \u25C6", "Increases Luck by 20.", Rarity.COMMON, 3),
    GOLD_GEAR_CHOKER_COMMON(31, "Gold Gear Choker \u25C6", "Increases Luck by 25.", Rarity.COMMON, 3),
    GARNET_COMMON(32, "Garnet \u25C6", "Restores 4% HP of damage dealt after a successful auto-attack.", Rarity.COMMON, 8),
    SAPPHIRE_COMMON(33, "Sapphire \u25C6", "Restores 6% HP of damage dealt after a successful auto-attack.", Rarity.COMMON, 8),
    DIAMOND_COMMON(34, "Diamond \u25C6", "Restores 8% HP of damage dealt after a successful auto-attack.", Rarity.COMMON, 8),
    CLASSIC_MEDAL_COMMON(35, "Classic Medal \u25C6", "Absorbs 10% of critical damage dealt as HP.", Rarity.COMMON, 9),
    MODERN_MEDAL_COMMON(36, "Modern Medal \u25C6", "Absorbs 15% of critical damage dealt as HP.", Rarity.COMMON, 9),
    AVANT_GARDE_MEDAL_COMMON(37, "Avant-Garde Medal \u25C6", "Absorbs 20% of critical damage dealt as HP.", Rarity.COMMON, 9),
    IRON_HEADBAND_COMMON(38, "Iron Headband \u25C6", "Increases critical damage by 20%.", Rarity.COMMON, 1),
    ICE_HEADBAND_COMMON(39, "Ice Headband \u25C6", "Increases critical damage by 30%.", Rarity.COMMON, 1),
    OPTICAL_HEADBAND_COMMON(40, "Optical Headband \u25C6", "Increases critical damage by 40%.", Rarity.COMMON, 1),
    MOON_CUBE_COMMON(41, "Moon Cube \u25C6", "Adds a 20% chance of attacking again after a successful auto-attack.", Rarity.COMMON, 7),
    STAR_CUBE_COMMON(42, "Star Cube \u25C6", "Adds a 35% chance of attacking again after a successful auto-attack.", Rarity.COMMON, 7),
    GALAXY_CUBE_COMMON(43, "Galaxy Cube \u25C6", "Adds a 50% chance of attacking again after a successful auto-attack.", Rarity.COMMON, 7),
    MECHANIZED_GREAVES_COMMON(44, "Mechanized Greaves \u25C6", "Increases damage dealt to toppled enemies by 50%.", Rarity.COMMON, 0),
    CRYSTAL_GREAVES_COMMON(45, "Crystal Greaves \u25C6", "Increases damage dealt to toppled enemies by 75%.", Rarity.COMMON, 0),
    GRAPHITE_GREAVES_COMMON(46, "Graphite Greaves \u25C6", "Increases damage dealt to toppled enemies by 100%.", Rarity.COMMON, 0),
    SWORDFIGHTING_BANNER_COMMON(47, "Swordfighting Banner \u25C6", "Increases damage dealt to launched enemies by 50%.", Rarity.COMMON, 5),
    GODDESS_BANNER_COMMON(48, "Goddess Banner \u25C6", "Increases damage dealt to launched enemies by 75%.", Rarity.COMMON, 5),
    ANCIENT_BANNER_COMMON(49, "Ancient Banner \u25C6", "Increases damage dealt to launched enemies by 100%.", Rarity.COMMON, 5),
    SPIKED_PAULDRONS_COMMON(50, "Spiked Pauldrons \u25C6", "Increases smash damage by 50%.", Rarity.COMMON, 2),
    HERO_PAULDRONS_COMMON(51, "Hero Pauldrons \u25C6", "Increases smash damage by 75%.", Rarity.COMMON, 2),
    JET_PAULDRONS_COMMON(52, "Jet Pauldrons \u25C6", "Increases smash damage by 100%.", Rarity.COMMON, 2),
    APPRENTICE_VAMBRACES_COMMON(53, "Apprentice Vambraces \u25C6", "Increases damage dealt to higher-level enemies by 20%.", Rarity.COMMON, 6),
    BOXER_VAMBRACES_COMMON(54, "Boxer Vambraces \u25C6", "Increases damage dealt to higher-level enemies by 35%.", Rarity.COMMON, 6),
    HERO_VAMBRACES_COMMON(55, "Hero Vambraces \u25C6", "Increases damage dealt to higher-level enemies by 50%.", Rarity.COMMON, 6),
    DARK_ORB_COMMON(56, "Dark Orb \u25C6", "Increases damage dealt when an ally is incapacitated by 50%.", Rarity.COMMON, 8),
    ERASER_ORB_COMMON(57, "Eraser Orb \u25C6", "Increases damage dealt when an ally is incapacitated by 100%.", Rarity.COMMON, 8),
    BLOODY_ORB_COMMON(58, "Bloody Orb \u25C6", "Increases damage dealt when an ally is incapacitated by 150%.", Rarity.COMMON, 8),
    CHROME_SCARF_COMMON(59, "Chrome Scarf \u25C6", "Extends Break duration by 15%.", Rarity.COMMON, 3),
    UNICORN_SCARF_COMMON(60, "Unicorn Scarf \u25C6", "Extends Break duration by 30%.", Rarity.COMMON, 3),
    QUANTUM_SCARF_COMMON(61, "Quantum Scarf \u25C6", "Extends Break duration by 45%.", Rarity.COMMON, 3),
    WHITE_BELT_COMMON(62, "White Belt \u25C6", "Extends Topple duration by 15%.", Rarity.COMMON, 4),
    BLACK_BELT_COMMON(63, "Black Belt \u25C6", "Extends Topple duration by 20%.", Rarity.COMMON, 4),
    PLATINUM_BELT_COMMON(64, "Platinum Belt \u25C6", "Extends Topple duration by 25%.", Rarity.COMMON, 4),
    SOLDIER_RING_COMMON(65, "Soldier Ring \u25C6", "Extends Launch duration by 15%.", Rarity.COMMON, 8),
    BERSERK_RING_COMMON(66, "Berserk Ring \u25C6", "Extends Launch duration by 20%.", Rarity.COMMON, 8),
    TYRANT_RING_COMMON(67, "Tyrant Ring \u25C6", "Extends Launch duration by 25%.", Rarity.COMMON, 8),
    ATTACK_STONE_COMMON(68, "Attack Stone \u25C6", "Increases auto-attack damage by 20%.", Rarity.COMMON, 8),
    ASSAULT_STONE_COMMON(69, "Assault Stone \u25C6", "Increases auto-attack damage by 40%.", Rarity.COMMON, 8),
    BREAK_STONE_COMMON(70, "Break Stone \u25C6", "Increases auto-attack damage by 60%.", Rarity.COMMON, 8),
    WORLD_TREE_DROP_COMMON(71, "World Tree Drop \u25C6", "Increases damage dealt per Blade Switch by 10% (max: 250%).", Rarity.COMMON, 8),
    MALE_LOINCLOTH_COMMON(72, "Male Loincloth \u25C6", "Increases damage dealt while Blade is the opposite gender by 50%.", Rarity.COMMON, 5),
    CHARMING_SWIMSUIT_COMMON(73, "Charming Swimsuit \u25C6", "Increases damage dealt while Blade is the opposite gender by 50%.", Rarity.COMMON, 5),
    ALPHA_SCOPE_COMMON(74, "Alpha Scope \u25C6", "Reduces enemy Topple resist.", Rarity.COMMON, 1),
    GAMMA_SCOPE_COMMON(75, "Gamma Scope \u25C6", "Reduces enemy Launch resist.", Rarity.COMMON, 1),
    BEAST_HOOD_COMMON(76, "Beast Hood \u25C6", "Increases aggro reduction by 20%.", Rarity.COMMON, 1),
    CAMO_HOOD_COMMON(77, "Camo Hood \u25C6", "Increases aggro reduction by 25%.", Rarity.COMMON, 1),
    SKELETON_HOOD_COMMON(78, "Skeleton Hood \u25C6", "Increases aggro reduction by 30%.", Rarity.COMMON, 1),
    NOPON_MASK_COMMON(79, "Nopon Mask \u25C6", "Increases aggro every second. (Minor effect.)", Rarity.COMMON, 1),
    METAL_NOPON_MASK_COMMON(80, "Metal Nopon Mask \u25C6", "Increases aggro every second. (Medium effect.)", Rarity.COMMON, 1),
    GOLD_NOPON_MASK_COMMON(81, "Gold Nopon Mask \u25C6", "Increases aggro every second. (Major effect.)", Rarity.COMMON, 1),
    COLORFUL_FEATHER_COMMON(82, "Colorful Feather \u25C6", "Start each battle with aggro. (Minor effect.)", Rarity.COMMON, 9),
    SILVER_FEATHER_COMMON(83, "Silver Feather \u25C6", "Start each battle with aggro. (Medium effect.)", Rarity.COMMON, 9),
    PHANTOM_FEATHER_COMMON(84, "Phantom Feather \u25C6", "Start each battle with aggro. (Major effect.)", Rarity.COMMON, 9),
    GRANDARBOR_WARD_COMMON(85, "Grandarbor Ward \u25C6", "Increases the HP restored when being revived by 25%.", Rarity.COMMON, 9),
    SPIRIT_TREE_WARD_COMMON(86, "Spirit Tree Ward \u25C6", "Increases the HP restored when being revived by 35%.", Rarity.COMMON, 9),
    WORLD_TREE_WARD_COMMON(87, "World Tree Ward \u25C6", "Increases the HP restored when being revived by 45%.", Rarity.COMMON, 9),
    FRIENDSHIP_RING_COMMON(88, "Friendship Ring \u25C6", "Increases the HP restored when reviving a teammate by 25%.", Rarity.COMMON, 8),
    AFFECTION_RING_COMMON(89, "Affection Ring \u25C6", "Increases the HP restored when reviving a teammate by 35%.", Rarity.COMMON, 8),
    PROMISE_RING_COMMON(90, "Promise Ring \u25C6", "Increases the HP restored when reviving a teammate by 45%.", Rarity.COMMON, 8),
    HARVEST_NECKLACE_COMMON(91, "Harvest Necklace \u25C6", "Improves the effect of Healing Arts by 10%.", Rarity.COMMON, 3),
    AFFECTION_NECKLACE_COMMON(92, "Affection Necklace \u25C6", "Improves the effect of Healing Arts by 15%.", Rarity.COMMON, 3),
    HOLY_NECKLACE_COMMON(93, "Holy Necklace \u25C6", "Improves the effect of Healing Arts by 20%.", Rarity.COMMON, 3),
    SHELL_CAMEO_COMMON(94, "Shell Cameo \u25C6", "Increases HP restored to self (not using HP Potions) by 10%.", Rarity.COMMON, 9),
    CHIVALRIC_MEDAL_COMMON(95, "Chivalric Medal \u25C6", "Restores 3% HP when canceling an auto-attack with a Driver Art.", Rarity.COMMON, 9),
    MILITARY_MEDAL_COMMON(96, "Military Medal \u25C6", "Restores 4% HP when canceling an auto-attack with a Driver Art.", Rarity.COMMON, 9),
    ROUND_TABLE_MEDAL_COMMON(97, "Round Table Medal \u25C6", "Restores 5% HP when canceling an auto-attack with a Driver Art.", Rarity.COMMON, 9),
    GAUNTLET_COMMON(98, "Gauntlet \u25C6", "Boosts recharge for Specials after canceling by 20%.", Rarity.COMMON, 6),
    BIO_GAUNTLET_COMMON(99, "Bio Gauntlet \u25C6", "Boosts recharge for Specials after canceling by 30%.", Rarity.COMMON, 6),
    NANO_METAL_GAUNTLET_COMMON(100, "Nano-Metal Gauntlet \u25C6", "Boosts recharge for Specials after canceling by 40%.", Rarity.COMMON, 6),
    EYEPATCH_COMMON(101, "Eyepatch \u25C6", "Adds 20% to damage ratio after canceling an auto-attack.", Rarity.COMMON, 1),
    LEADERS_EYEPATCH_COMMON(102, "Leader's Eyepatch \u25C6", "Adds 35% to damage ratio after canceling an auto-attack.", Rarity.COMMON, 1),
    HI_TECH_EYEPATCH_COMMON(103, "Hi-Tech Eyepatch \u25C6", "Adds 50% to damage ratio after canceling an auto-attack.", Rarity.COMMON, 1),
    REVIVAL_POD_LEGENDARY(104, "Revival Pod \u25C6\u25C6\u25C6", "100% chance to survive hit with 1 HP + 5 secs invincibility (once per battle).", Rarity.LEGENDARY, 7),
    ZERO_BATTLE_COURSE_COMMON(105, "0-Battle Course \u25C6", "Boosts experience received from defeating enemies by 25%.", Rarity.COMMON, 7),
    ZERO_BATTLE_COURSEPLUS_COMMON(106, "0-Battle Course+ \u25C6", "Boosts experience received from defeating enemies by 50%.", Rarity.COMMON, 7),
    ALPHABET_COURSE_COMMON(107, "Alphabet Course \u25C6", "Boosts WP received from defeating enemies by 25%.", Rarity.COMMON, 5),
    ALPHABET_COURSEPLUS_COMMON(108, "Alphabet Course+ \u25C6", "Boosts WP received from defeating enemies by 50%.", Rarity.COMMON, 5),
    SILVER_EARRINGS_COMMON(109, "Silver Earrings \u25C6", "Fills Party Gauge on \"Excellent\" Specials. (Minor effect.)", Rarity.COMMON, 8),
    CRYSTAL_EARRINGS_COMMON(110, "Crystal Earrings \u25C6", "Fills Party Gauge on \"Excellent\" Specials. (Major effect.)", Rarity.COMMON, 8),
    OMEGA_DRIVE_COMMON(111, "Omega Drive \u25C6", "Slightly fills the Party Gauge for each critical hit delivered.", Rarity.COMMON, 7),
    SIGMA_DRIVE_COMMON(112, "Sigma Drive \u25C6", "Slightly fills the Party Gauge for each Driver Art used.", Rarity.COMMON, 7),
    BURST_SYMBOL_COMMON(113, "Burst Symbol \u25C6", "Increases attack power ratio at the start of a Chain Attack.", Rarity.COMMON, 9),
    CRITICAL_SYMBOL_COMMON(114, "Critical Symbol \u25C6", "Increases critical hit rate during a Chain Attack by 50%.", Rarity.COMMON, 9),
    RECOVERY_SYMBOL_COMMON(115, "Recovery Symbol \u25C6", "Heals 50% HP each time a Chain Attack is initiated.", Rarity.COMMON, 9),
    RESURRECTION_SYMBOL_LEGENDARY(116, "Resurrection Symbol \u25C6\u25C6\u25C6", "Revives Driver each time a Chain Attack is initiated.", Rarity.LEGENDARY, 9),
    INFINITY_SYMBOL_COMMON(117, "Infinity Symbol \u25C6", "Slightly fills the Party Gauge at the end of each Chain Attack.", Rarity.COMMON, 9),
    AUTO_BALANCER_LEGENDARY(118, "Auto-Balancer \u25C6\u25C6\u25C6", "Prevents deflections when an enemy guards an attack.", Rarity.LEGENDARY, 7),
    SWORD_ATTACHMENT_COMMON(119, "Sword Attachment \u25C6", "Increases attack power of Aegis Sword-class weapons by 25%.", Rarity.COMMON, 7),
    SCIMITAR_ATTACHMENT_COMMON(120, "Scimitar Attachment \u25C6", "Increases attack power of Catalyst Scimitar-class weapons by 25%.", Rarity.COMMON, 7),
    RING_ATTACHMENT_COMMON(121, "Ring Attachment \u25C6", "Increases attack power of Twin Rings-class weapons by 25%.", Rarity.COMMON, 7),
    SHIELD_ATTACHMENT_COMMON(122, "Shield Attachment \u25C6", "Increases attack power of Drill Shield-class weapons by 25%.", Rarity.COMMON, 7),
    ARMS_ATTACHMENT_COMMON(123, "Arms Attachment \u25C6", "Increases attack power of Mech Arms-class weapons by 25%.", Rarity.COMMON, 7),
    SABER_ATTACHMENT_COMMON(124, "Saber Attachment \u25C6", "Increases attack power of Variable Saber-class weapons by 25%.", Rarity.COMMON, 7),
    WHIP_ATTACHMENT_COMMON(125, "Whip Attachment \u25C6", "Increases attack power of Whipsword-class weapons by 25%.", Rarity.COMMON, 7),
    EDGE_ATTACHMENT_COMMON(126, "Edge Attachment \u25C6", "Increases attack power of Big Bang Edge-class weapons by 25%.", Rarity.COMMON, 7),
    SCYTHE_ATTACHMENT_COMMON(127, "Scythe Attachment \u25C6", "Increases attack power of Dual Scythes-class weapons by 25%.", Rarity.COMMON, 7),
    AXE_ATTACHMENT_COMMON(128, "Axe Attachment \u25C6", "Increases attack power of Greataxe-class weapons by 25%.", Rarity.COMMON, 7),
    LANCE_ATTACHMENT_COMMON(129, "Lance Attachment \u25C6", "Increases attack power of Megalance-class weapons by 25%.", Rarity.COMMON, 7),
    CANNON_ATTACHMENT_COMMON(130, "Cannon Attachment \u25C6", "Increases attack power of Ether Cannon-class weapons by 25%.", Rarity.COMMON, 7),
    HAMMER_ATTACHMENT_COMMON(131, "Hammer Attachment \u25C6", "Increases attack power of Shield Hammer-class weapons by 25%.", Rarity.COMMON, 7),
    KATANA_ATTACHMENT_COMMON(132, "Katana Attachment \u25C6", "Increases attack power of Chroma Katana-class weapons by 25%.", Rarity.COMMON, 7),
    BALL_ATTACHMENT_COMMON(133, "Ball Attachment \u25C6", "Increases attack power of Bitball-class weapons by 25%.", Rarity.COMMON, 7),
    KNUCKLE_ATTACHMENT_COMMON(134, "Knuckle Attachment \u25C6", "Increases attack power of Knuckle Claws-class weapons by 25%.", Rarity.COMMON, 7),
    MASTER_ATTACHMENT_COMMON(135, "Master Attachment \u25C6", "Increases the attack power of all weapon classes by 10%.", Rarity.COMMON, 7),
    MEMORY_LOCKET_LEGENDARY(136, "Memory Locket \u25C6\u25C6\u25C6", "Prevents Affinity loss when a teammate falls in battle.", Rarity.LEGENDARY, 3),
    CHEER_TREAT_COMMON(137, "Cheer Treat \u25C6", "Increases Affinity by 50% after winning a Special button challenge.", Rarity.COMMON, 5),
    RED_THREAD_COMMON(138, "Red Thread \u25C6", "Extends the range of Driver-Blade Affinity by 100cm.", Rarity.COMMON, 5),
    LOVE_THREAD_COMMON(139, "Love Thread \u25C6", "Extends the range of Driver-Blade Affinity by 150cm.", Rarity.COMMON, 5),
    PASSION_THREAD_COMMON(140, "Passion Thread \u25C6", "Extends the range of Driver-Blade Affinity by 200cm.", Rarity.COMMON, 5),
    ACTIVITY_AMULET_COMMON(141, "Activity Amulet \u25C6", "Boosts the effect of HP Potions by 20%.", Rarity.COMMON, 8),
    HEALING_AMULET_COMMON(142, "Healing Amulet \u25C6", "Boosts the effect of HP Potions by 30%.", Rarity.COMMON, 8),
    REBIRTH_AMULET_COMMON(143, "Rebirth Amulet \u25C6", "Boosts the effect of HP Potions by 40%.", Rarity.COMMON, 8),
    BETA_SCOPE_COMMON(144, "Beta Scope \u25C6", "Reduces enemy Break resist.", Rarity.COMMON, 1),
    RUSH_HOUR_COMMON(145, "Rush Hour \u25C6", "Expands the window of opportunity for canceling by 50%.", Rarity.COMMON, 7),
    APPEALING_LAMP_COMMON(146, "Appealing Lamp \u25C6", "Adds 25% buffer time to combos if switching to a combo-requesting Blade.", Rarity.COMMON, 5),
    OVERCLOCKING_BANGLE_COMMON(147, "Overclocking Bangle \u25C6", "Shortens cooldown time relative to the no. of Arts ready after a Blade Switch.", Rarity.COMMON, 6),
    MINT_POTPOURRI_COMMON(148, "Mint Potpourri \u25C6", "Boosts taunt resistance by 60%.", Rarity.COMMON, 5),
    LAVENDER_POTPOURRI_COMMON(149, "Lavender Potpourri \u25C6", "Boosts taunt resistance by 90%.", Rarity.COMMON, 5),
    PRIESTESSS_AUSPICES_COMMON(150, "Priestess's Auspices \u25C6", "Boosts Driver shackle resistance by 60%.", Rarity.COMMON, 3),
    SAGES_AUSPICES_COMMON(151, "Sage's Auspices \u25C6", "Boosts Driver shackle resistance by 90%.", Rarity.COMMON, 3),
    INCENSE_OF_CALM_COMMON(152, "Incense of Calm \u25C6", "Increases resistance to Stench by 60%.", Rarity.COMMON, 5),
    INCENSE_OF_INSIGHT_COMMON(153, "Incense of Insight \u25C6", "Increases resistance to Stench by 90%.", Rarity.COMMON, 5),
    GEAR_VEST_RARE(154, "Gear Vest \u25C6\u25C6", "Boosts maximum HP by 21%.", Rarity.RARE, 2),
    JADE_VEST_RARE(155, "Jade Vest \u25C6\u25C6", "Boosts maximum HP by 26%.", Rarity.RARE, 2),
    TITANIUM_VEST_RARE(156, "Titanium Vest \u25C6\u25C6", "Boosts maximum HP by 31%.", Rarity.RARE, 2),
    STEAM_BELT_RARE(157, "Steam Belt \u25C6\u25C6", "Boosts Strength by 21%.", Rarity.RARE, 4),
    SILVER_BELT_RARE(158, "Silver Belt \u25C6\u25C6", "Boosts Strength by 26%.", Rarity.RARE, 4),
    CERAMIC_BELT_RARE(159, "Ceramic Belt \u25C6\u25C6", "Boosts Strength by 31%.", Rarity.RARE, 4),
    BOLT_HAT_RARE(160, "Bolt Hat \u25C6\u25C6", "Boosts Ether by 21%.", Rarity.RARE, 1),
    PEARL_HAT_RARE(161, "Pearl Hat \u25C6\u25C6", "Boosts Ether by 26%.", Rarity.RARE, 1),
    FIBER_HAT_RARE(162, "Fiber Hat \u25C6\u25C6", "Boosts Ether by 31%.", Rarity.RARE, 1),
    RAINBOW_GLOVES_RARE(163, "Rainbow Gloves \u25C6\u25C6", "Boosts Dexterity by 21%.", Rarity.RARE, 6),
    HERO_GLOVES_RARE(164, "Hero Gloves \u25C6\u25C6", "Boosts Dexterity by 26%.", Rarity.RARE, 6),
    CARBON_GLOVES_RARE(165, "Carbon Gloves \u25C6\u25C6", "Boosts Dexterity by 31%.", Rarity.RARE, 6),
    SHELL_SHOES_RARE(166, "Shell Shoes \u25C6\u25C6", "Boosts Agility by 21%.", Rarity.RARE, 0),
    ASSASSIN_SHOES_RARE(167, "Assassin Shoes \u25C6\u25C6", "Boosts Agility by 26%.", Rarity.RARE, 0),
    ESTER_SHOES_RARE(168, "Ester Shoes \u25C6\u25C6", "Boosts Agility by 31%.", Rarity.RARE, 0),
    NACRE_CHOKER_RARE(169, "Nacre Choker \u25C6\u25C6", "Boosts Luck by 21%.", Rarity.RARE, 3),
    GODDESS_CHOKER_RARE(170, "Goddess Choker \u25C6\u25C6", "Boosts Luck by 26%.", Rarity.RARE, 3),
    COMET_CHOKER_RARE(171, "Comet Choker \u25C6\u25C6", "Boosts Luck by 31%.", Rarity.RARE, 3),
    RIGID_VEST_RARE(172, "Rigid Vest \u25C6\u25C6", "Increases maximum HP by 250.", Rarity.RARE, 2),
    INFANTRY_VEST_RARE(173, "Infantry Vest \u25C6\u25C6", "Increases maximum HP by 450.", Rarity.RARE, 2),
    MUSCLE_BELT_RARE(174, "Muscle Belt \u25C6\u25C6", "Increases Strength by 21.", Rarity.RARE, 4),
    CHAMPION_BELT_RARE(175, "Champion Belt \u25C6\u25C6", "Increases Strength by 26.", Rarity.RARE, 4),
    FLUFFY_HAT_RARE(176, "Fluffy Hat \u25C6\u25C6", "Increases Ether by 21.", Rarity.RARE, 1),
    FABULOUS_HAT_RARE(177, "Fabulous Hat \u25C6\u25C6", "Increases Ether by 26.", Rarity.RARE, 1),
    LEATHER_GLOVES_RARE(178, "Leather Gloves \u25C6\u25C6", "Increases Dexterity by 21.", Rarity.RARE, 6),
    SMITHY_GLOVES_RARE(179, "Smithy Gloves \u25C6\u25C6", "Increases Dexterity by 26.", Rarity.RARE, 6),
    WOLF_SHOES_RARE(180, "Wolf Shoes \u25C6\u25C6", "Increases Agility by 11.", Rarity.RARE, 0),
    SPRING_SHOES_RARE(181, "Spring Shoes \u25C6\u25C6", "Increases Agility by 16.", Rarity.RARE, 0),
    BUNNIT_CHOKER_RARE(182, "Bunnit Choker \u25C6\u25C6", "Increases Luck by 21.", Rarity.RARE, 3),
    GOLD_GEAR_CHOKER_RARE(183, "Gold Gear Choker \u25C6\u25C6", "Increases Luck by 26.", Rarity.RARE, 3),
    GARNET_RARE(184, "Garnet \u25C6\u25C6", "Restores 4.5% HP of damage dealt after a successful auto-attack.", Rarity.RARE, 8),
    SAPPHIRE_RARE(185, "Sapphire \u25C6\u25C6", "Restores 6.5% HP of damage dealt after a successful auto-attack.", Rarity.RARE, 8),
    DIAMOND_RARE(186, "Diamond \u25C6\u25C6", "Restores 8.5% HP of damage dealt after a successful auto-attack.", Rarity.RARE, 8),
    CLASSIC_MEDAL_RARE(187, "Classic Medal \u25C6\u25C6", "Absorbs 11% of critical damage dealt as HP.", Rarity.RARE, 9),
    MODERN_MEDAL_RARE(188, "Modern Medal \u25C6\u25C6", "Absorbs 16% of critical damage dealt as HP.", Rarity.RARE, 9),
    AVANT_GARDE_MEDAL_RARE(189, "Avant-Garde Medal \u25C6\u25C6", "Absorbs 21% of critical damage dealt as HP.", Rarity.RARE, 9),
    IRON_HEADBAND_RARE(190, "Iron Headband \u25C6\u25C6", "Increases critical damage by 25%.", Rarity.RARE, 1),
    ICE_HEADBAND_RARE(191, "Ice Headband \u25C6\u25C6", "Increases critical damage by 35%.", Rarity.RARE, 1),
    OPTICAL_HEADBAND_RARE(192, "Optical Headband \u25C6\u25C6", "Increases critical damage by 45%.", Rarity.RARE, 1),
    MOON_CUBE_RARE(193, "Moon Cube \u25C6\u25C6", "Adds a 25% chance of attacking again after a successful auto-attack.", Rarity.RARE, 7),
    STAR_CUBE_RARE(194, "Star Cube \u25C6\u25C6", "Adds a 40% chance of attacking again after a successful auto-attack.", Rarity.RARE, 7),
    GALAXY_CUBE_RARE(195, "Galaxy Cube \u25C6\u25C6", "Adds a 55% chance of attacking again after a successful auto-attack.", Rarity.RARE, 7),
    MECHANIZED_GREAVES_RARE(196, "Mechanized Greaves \u25C6\u25C6", "Increases damage dealt to toppled enemies by 55%.", Rarity.RARE, 0),
    CRYSTAL_GREAVES_RARE(197, "Crystal Greaves \u25C6\u25C6", "Increases damage dealt to toppled enemies by 80%.", Rarity.RARE, 0),
    GRAPHITE_GREAVES_RARE(198, "Graphite Greaves \u25C6\u25C6", "Increases damage dealt to toppled enemies by 105%.", Rarity.RARE, 0),
    SWORDFIGHTING_BANNER_RARE(199, "Swordfighting Banner \u25C6\u25C6", "Increases damage dealt to launched enemies by 55%.", Rarity.RARE, 5),
    GODDESS_BANNER_RARE(200, "Goddess Banner \u25C6\u25C6", "Increases damage dealt to launched enemies by 80%.", Rarity.RARE, 5),
    ANCIENT_BANNER_RARE(201, "Ancient Banner \u25C6\u25C6", "Increases damage dealt to launched enemies by 105%.", Rarity.RARE, 5),
    SPIKED_PAULDRONS_RARE(202, "Spiked Pauldrons \u25C6\u25C6", "Increases smash damage by 55%.", Rarity.RARE, 2),
    HERO_PAULDRONS_RARE(203, "Hero Pauldrons \u25C6\u25C6", "Increases smash damage by 80%.", Rarity.RARE, 2),
    JET_PAULDRONS_RARE(204, "Jet Pauldrons \u25C6\u25C6", "Increases smash damage by 105%.", Rarity.RARE, 2),
    APPRENTICE_VAMBRACES_RARE(205, "Apprentice Vambraces \u25C6\u25C6", "Increases damage dealt to higher-level enemies by 25%.", Rarity.RARE, 6),
    BOXER_VAMBRACES_RARE(206, "Boxer Vambraces \u25C6\u25C6", "Increases damage dealt to higher-level enemies by 40%.", Rarity.RARE, 6),
    HERO_VAMBRACES_RARE(207, "Hero Vambraces \u25C6\u25C6", "Increases damage dealt to higher-level enemies by 55%.", Rarity.RARE, 6),
    DARK_ORB_RARE(208, "Dark Orb \u25C6\u25C6", "Increases damage dealt when an ally is incapacitated by 55%.", Rarity.RARE, 8),
    ERASER_ORB_RARE(209, "Eraser Orb \u25C6\u25C6", "Increases damage dealt when an ally is incapacitated by 105%.", Rarity.RARE, 8),
    BLOODY_ORB_RARE(210, "Bloody Orb \u25C6\u25C6", "Increases damage dealt when an ally is incapacitated by 155%.", Rarity.RARE, 8),
    CHROME_SCARF_RARE(211, "Chrome Scarf \u25C6\u25C6", "Extends Break duration by 17%.", Rarity.RARE, 3),
    UNICORN_SCARF_RARE(212, "Unicorn Scarf \u25C6\u25C6", "Extends Break duration by 32%.", Rarity.RARE, 3),
    QUANTUM_SCARF_RARE(213, "Quantum Scarf \u25C6\u25C6", "Extends Break duration by 47%.", Rarity.RARE, 3),
    WHITE_BELT_RARE(214, "White Belt \u25C6\u25C6", "Extends Topple duration by 16%.", Rarity.RARE, 4),
    BLACK_BELT_RARE(215, "Black Belt \u25C6\u25C6", "Extends Topple duration by 21%.", Rarity.RARE, 4),
    PLATINUM_BELT_RARE(216, "Platinum Belt \u25C6\u25C6", "Extends Topple duration by 26%.", Rarity.RARE, 4),
    SOLDIER_RING_RARE(217, "Soldier Ring \u25C6\u25C6", "Extends Launch duration by 16%.", Rarity.RARE, 8),
    BERSERK_RING_RARE(218, "Berserk Ring \u25C6\u25C6", "Extends Launch duration by 21%.", Rarity.RARE, 8),
    TYRANT_RING_RARE(219, "Tyrant Ring \u25C6\u25C6", "Extends Launch duration by 26%.", Rarity.RARE, 8),
    ATTACK_STONE_RARE(220, "Attack Stone \u25C6\u25C6", "Increases auto-attack damage by 25%.", Rarity.RARE, 8),
    ASSAULT_STONE_RARE(221, "Assault Stone \u25C6\u25C6", "Increases auto-attack damage by 45%.", Rarity.RARE, 8),
    BREAK_STONE_RARE(222, "Break Stone \u25C6\u25C6", "Increases auto-attack damage by 65%.", Rarity.RARE, 8),
    WORLD_TREE_DROP_RARE(223, "World Tree Drop \u25C6\u25C6", "Increases damage dealt per Blade Switch by 11% (max: 250%).", Rarity.RARE, 8),
    MALE_LOINCLOTH_RARE(224, "Male Loincloth \u25C6\u25C6", "Increases damage dealt while Blade is the opposite gender by 55%.", Rarity.RARE, 5),
    CHARMING_SWIMSUIT_RARE(225, "Charming Swimsuit \u25C6\u25C6", "Increases damage dealt while Blade is the opposite gender by 55%.", Rarity.RARE, 5),
    ALPHA_SCOPE_RARE(226, "Alpha Scope \u25C6\u25C6", "Reduces enemy Topple resist.", Rarity.RARE, 1),
    GAMMA_SCOPE_RARE(227, "Gamma Scope \u25C6\u25C6", "Reduces enemy Launch resist.", Rarity.RARE, 1),
    BEAST_HOOD_RARE(228, "Beast Hood \u25C6\u25C6", "Increases aggro reduction by 21%.", Rarity.RARE, 1),
    CAMO_HOOD_RARE(229, "Camo Hood \u25C6\u25C6", "Increases aggro reduction by 26%.", Rarity.RARE, 1),
    SKELETON_HOOD_RARE(230, "Skeleton Hood \u25C6\u25C6", "Increases aggro reduction by 31%.", Rarity.RARE, 1),
    NOPON_MASK_RARE(231, "Nopon Mask \u25C6\u25C6", "Increases aggro every second. (Minor effect.)", Rarity.RARE, 1),
    METAL_NOPON_MASK_RARE(232, "Metal Nopon Mask \u25C6\u25C6", "Increases aggro every second. (Medium effect.)", Rarity.RARE, 1),
    GOLD_NOPON_MASK_RARE(233, "Gold Nopon Mask \u25C6\u25C6", "Increases aggro every second. (Major effect.)", Rarity.RARE, 1),
    COLORFUL_FEATHER_RARE(234, "Colorful Feather \u25C6\u25C6", "Start each battle with aggro. (Minor effect.)", Rarity.RARE, 9),
    SILVER_FEATHER_RARE(235, "Silver Feather \u25C6\u25C6", "Start each battle with aggro. (Medium effect.)", Rarity.RARE, 9),
    PHANTOM_FEATHER_RARE(236, "Phantom Feather \u25C6\u25C6", "Start each battle with aggro. (Major effect.)", Rarity.RARE, 9),
    GRANDARBOR_WARD_RARE(237, "Grandarbor Ward \u25C6\u25C6", "Increases the HP restored when being revived by 27%.", Rarity.RARE, 9),
    SPIRIT_TREE_WARD_RARE(238, "Spirit Tree Ward \u25C6\u25C6", "Increases the HP restored when being revived by 37%.", Rarity.RARE, 9),
    WORLD_TREE_WARD_RARE(239, "World Tree Ward \u25C6\u25C6", "Increases the HP restored when being revived by 47%.", Rarity.RARE, 9),
    FRIENDSHIP_RING_RARE(240, "Friendship Ring \u25C6\u25C6", "Increases the HP restored when reviving a teammate by 27%.", Rarity.RARE, 8),
    AFFECTION_RING_RARE(241, "Affection Ring \u25C6\u25C6", "Increases the HP restored when reviving a teammate by 37%.", Rarity.RARE, 8),
    PROMISE_RING_RARE(242, "Promise Ring \u25C6\u25C6", "Increases the HP restored when reviving a teammate by 47%.", Rarity.RARE, 8),
    HARVEST_NECKLACE_RARE(243, "Harvest Necklace \u25C6\u25C6", "Improves the effect of Healing Arts by 12%.", Rarity.RARE, 3),
    AFFECTION_NECKLACE_RARE(244, "Affection Necklace \u25C6\u25C6", "Improves the effect of Healing Arts by 17%.", Rarity.RARE, 3),
    HOLY_NECKLACE_RARE(245, "Holy Necklace \u25C6\u25C6", "Improves the effect of Healing Arts by 22%.", Rarity.RARE, 3),
    SHELL_CAMEO_RARE(246, "Shell Cameo \u25C6\u25C6", "Increases HP restored to self (not using HP Potions) by 12%.", Rarity.RARE, 9),
    CHIVALRIC_MEDAL_RARE(247, "Chivalric Medal \u25C6\u25C6", "Restores 3.2% HP when canceling an auto-attack with a Driver Art.", Rarity.RARE, 9),
    MILITARY_MEDAL_RARE(248, "Military Medal \u25C6\u25C6", "Restores 4.2% HP when canceling an auto-attack with a Driver Art.", Rarity.RARE, 9),
    ROUND_TABLE_MEDAL_RARE(249, "Round Table Medal \u25C6\u25C6", "Restores 5.2% HP when canceling an auto-attack with a Driver Art.", Rarity.RARE, 9),
    GAUNTLET_RARE(250, "Gauntlet \u25C6\u25C6", "Boosts recharge for Specials after canceling by 22%.", Rarity.RARE, 6),
    BIO_GAUNTLET_RARE(251, "Bio Gauntlet \u25C6\u25C6", "Boosts recharge for Specials after canceling by 32%.", Rarity.RARE, 6),
    NANO_METAL_GAUNTLET_RARE(252, "Nano-Metal Gauntlet \u25C6\u25C6", "Boosts recharge for Specials after canceling by 42%.", Rarity.RARE, 6),
    EYEPATCH_RARE(253, "Eyepatch \u25C6\u25C6", "Adds 22% to damage ratio after canceling an auto-attack.", Rarity.RARE, 1),
    LEADERS_EYEPATCH_RARE(254, "Leader's Eyepatch \u25C6\u25C6", "Adds 37% to damage ratio after canceling an auto-attack.", Rarity.RARE, 1),
    HI_TECH_EYEPATCH_RARE(255, "Hi-Tech Eyepatch \u25C6\u25C6", "Adds 52% to damage ratio after canceling an auto-attack.", Rarity.RARE, 1),
    SILVER_EARRINGS_RARE(256, "Silver Earrings \u25C6\u25C6", "Fills Party Gauge on \"Excellent\" Specials. (Minor effect.)", Rarity.RARE, 8),
    CRYSTAL_EARRINGS_RARE(257, "Crystal Earrings \u25C6\u25C6", "Fills Party Gauge on \"Excellent\" Specials. (Major effect.)", Rarity.RARE, 8),
    OMEGA_DRIVE_RARE(258, "Omega Drive \u25C6\u25C6", "Slightly fills the Party Gauge for each critical hit delivered.", Rarity.RARE, 7),
    SIGMA_DRIVE_RARE(259, "Sigma Drive \u25C6\u25C6", "Slightly fills the Party Gauge for each Driver Art used.", Rarity.RARE, 7),
    BURST_SYMBOL_RARE(260, "Burst Symbol \u25C6\u25C6", "Increases attack power ratio at the start of a Chain Attack.", Rarity.RARE, 9),
    CRITICAL_SYMBOL_RARE(261, "Critical Symbol \u25C6\u25C6", "Increases critical hit rate during a Chain Attack by 52%.", Rarity.RARE, 9),
    RECOVERY_SYMBOL_RARE(262, "Recovery Symbol \u25C6\u25C6", "Heals 55% HP each time a Chain Attack is initiated.", Rarity.RARE, 9),
    INFINITY_SYMBOL_RARE(263, "Infinity Symbol \u25C6\u25C6", "Slightly fills the Party Gauge at the end of each Chain Attack.", Rarity.RARE, 9),
    SWORD_ATTACHMENT_RARE(264, "Sword Attachment \u25C6\u25C6", "Increases attack power of Aegis Sword-class weapons by 27%.", Rarity.RARE, 7),
    SCIMITAR_ATTACHMENT_RARE(265, "Scimitar Attachment \u25C6\u25C6", "Increases attack power of Catalyst Scimitar-class weapons by 27%.", Rarity.RARE, 7),
    RING_ATTACHMENT_RARE(266, "Ring Attachment \u25C6\u25C6", "Increases attack power of Twin Rings-class weapons by 27%.", Rarity.RARE, 7),
    SHIELD_ATTACHMENT_RARE(267, "Shield Attachment \u25C6\u25C6", "Increases attack power of Drill Shield-class weapons by 27%.", Rarity.RARE, 7),
    ARMS_ATTACHMENT_RARE(268, "Arms Attachment \u25C6\u25C6", "Increases attack power of Mech Arms-class weapons by 27%.", Rarity.RARE, 7),
    SABER_ATTACHMENT_RARE(269, "Saber Attachment \u25C6\u25C6", "Increases attack power of Variable Saber-class weapons by 27%.", Rarity.RARE, 7),
    WHIP_ATTACHMENT_RARE(270, "Whip Attachment \u25C6\u25C6", "Increases attack power of Whipsword-class weapons by 27%.", Rarity.RARE, 7),
    EDGE_ATTACHMENT_RARE(271, "Edge Attachment \u25C6\u25C6", "Increases attack power of Big Bang Edge-class weapons by 27%.", Rarity.RARE, 7),
    SCYTHE_ATTACHMENT_RARE(272, "Scythe Attachment \u25C6\u25C6", "Increases attack power of Dual Scythes-class weapons by 27%.", Rarity.RARE, 7),
    AXE_ATTACHMENT_RARE(273, "Axe Attachment \u25C6\u25C6", "Increases attack power of Greataxe-class weapons by 27%.", Rarity.RARE, 7),
    LANCE_ATTACHMENT_RARE(274, "Lance Attachment \u25C6\u25C6", "Increases attack power of Megalance-class weapons by 27%.", Rarity.RARE, 7),
    CANNON_ATTACHMENT_RARE(275, "Cannon Attachment \u25C6\u25C6", "Increases attack power of Ether Cannon-class weapons by 27%.", Rarity.RARE, 7),
    HAMMER_ATTACHMENT_RARE(276, "Hammer Attachment \u25C6\u25C6", "Increases attack power of Shield Hammer-class weapons by 27%.", Rarity.RARE, 7),
    KATANA_ATTACHMENT_RARE(277, "Katana Attachment \u25C6\u25C6", "Increases attack power of Chroma Katana-class weapons by 27%.", Rarity.RARE, 7),
    BALL_ATTACHMENT_RARE(278, "Ball Attachment \u25C6\u25C6", "Increases attack power of Bitball-class weapons by 27%.", Rarity.RARE, 7),
    KNUCKLE_ATTACHMENT_RARE(279, "Knuckle Attachment \u25C6\u25C6", "Increases attack power of Knuckle Claws-class weapons by 27%.", Rarity.RARE, 7),
    MASTER_ATTACHMENT_RARE(280, "Master Attachment \u25C6\u25C6", "Increases the attack power of all weapon classes by 12%.", Rarity.RARE, 7),
    CHEER_TREAT_RARE(281, "Cheer Treat \u25C6\u25C6", "Increases Affinity by 55% after winning a Special button challenge.", Rarity.RARE, 5),
    RED_THREAD_RARE(282, "Red Thread \u25C6\u25C6", "Extends the range of Driver-Blade Affinity by 110cm.", Rarity.RARE, 5),
    LOVE_THREAD_RARE(283, "Love Thread \u25C6\u25C6", "Extends the range of Driver-Blade Affinity by 160cm.", Rarity.RARE, 5),
    PASSION_THREAD_RARE(284, "Passion Thread \u25C6\u25C6", "Extends the range of Driver-Blade Affinity by 210cm.", Rarity.RARE, 5),
    ACTIVITY_AMULET_RARE(285, "Activity Amulet \u25C6\u25C6", "Boosts the effect of HP Potions by 22%.", Rarity.RARE, 8),
    HEALING_AMULET_RARE(286, "Healing Amulet \u25C6\u25C6", "Boosts the effect of HP Potions by 32%.", Rarity.RARE, 8),
    REBIRTH_AMULET_RARE(287, "Rebirth Amulet \u25C6\u25C6", "Boosts the effect of HP Potions by 42%.", Rarity.RARE, 8),
    BETA_SCOPE_RARE(288, "Beta Scope \u25C6\u25C6", "Reduces enemy Break resist.", Rarity.RARE, 1),
    RUSH_HOUR_RARE(289, "Rush Hour \u25C6\u25C6", "Expands the window of opportunity for canceling by 60%.", Rarity.RARE, 7),
    APPEALING_LAMP_RARE(290, "Appealing Lamp \u25C6\u25C6", "Adds 30% buffer time to combos if switching to a combo-requesting Blade.", Rarity.RARE, 5),
    OVERCLOCKING_BANGLE_RARE(291, "Overclocking Bangle \u25C6\u25C6", "Shortens cooldown time relative to the no. of Arts ready after a Blade Switch.", Rarity.RARE, 6),
    MINT_POTPOURRI_RARE(292, "Mint Potpourri \u25C6\u25C6", "Boosts taunt resistance by 65%.", Rarity.RARE, 5),
    LAVENDER_POTPOURRI_RARE(293, "Lavender Potpourri \u25C6\u25C6", "Boosts taunt resistance by 95%.", Rarity.RARE, 5),
    PRIESTESSS_AUSPICES_RARE(294, "Priestess's Auspices \u25C6\u25C6", "Boosts Driver shackle resistance by 65%.", Rarity.RARE, 3),
    SAGES_AUSPICES_RARE(295, "Sage's Auspices \u25C6\u25C6", "Boosts Driver shackle resistance by 95%.", Rarity.RARE, 3),
    INCENSE_OF_CALM_RARE(296, "Incense of Calm \u25C6\u25C6", "Increases resistance to Stench by 65%.", Rarity.RARE, 5),
    INCENSE_OF_INSIGHT_RARE(297, "Incense of Insight \u25C6\u25C6", "Increases resistance to Stench by 95%.", Rarity.RARE, 5),
    GEAR_VEST_LEGENDARY(298, "Gear Vest \u25C6\u25C6\u25C6", "Boosts maximum HP by 22%.", Rarity.LEGENDARY, 2),
    JADE_VEST_LEGENDARY(299, "Jade Vest \u25C6\u25C6\u25C6", "Boosts maximum HP by 27%.", Rarity.LEGENDARY, 2),
    TITANIUM_VEST_LEGENDARY(300, "Titanium Vest \u25C6\u25C6\u25C6", "Boosts maximum HP by 32%.", Rarity.LEGENDARY, 2),
    STEAM_BELT_LEGENDARY(301, "Steam Belt \u25C6\u25C6\u25C6", "Boosts Strength by 22%.", Rarity.LEGENDARY, 4),
    SILVER_BELT_LEGENDARY(302, "Silver Belt \u25C6\u25C6\u25C6", "Boosts Strength by 27%.", Rarity.LEGENDARY, 4),
    CERAMIC_BELT_LEGENDARY(303, "Ceramic Belt \u25C6\u25C6\u25C6", "Boosts Strength by 32%.", Rarity.LEGENDARY, 4),
    BOLT_HAT_LEGENDARY(304, "Bolt Hat \u25C6\u25C6\u25C6", "Boosts Ether by 22%.", Rarity.LEGENDARY, 1),
    PEARL_HAT_LEGENDARY(305, "Pearl Hat \u25C6\u25C6\u25C6", "Boosts Ether by 27%.", Rarity.LEGENDARY, 1),
    FIBER_HAT_LEGENDARY(306, "Fiber Hat \u25C6\u25C6\u25C6", "Boosts Ether by 32%.", Rarity.LEGENDARY, 1),
    RAINBOW_GLOVES_LEGENDARY(307, "Rainbow Gloves \u25C6\u25C6\u25C6", "Boosts Dexterity by 22%.", Rarity.LEGENDARY, 6),
    HERO_GLOVES_LEGENDARY(308, "Hero Gloves \u25C6\u25C6\u25C6", "Boosts Dexterity by 27%.", Rarity.LEGENDARY, 6),
    CARBON_GLOVES_LEGENDARY(309, "Carbon Gloves \u25C6\u25C6\u25C6", "Boosts Dexterity by 32%.", Rarity.LEGENDARY, 6),
    SHELL_SHOES_LEGENDARY(310, "Shell Shoes \u25C6\u25C6\u25C6", "Boosts Agility by 22%.", Rarity.LEGENDARY, 0),
    ASSASSIN_SHOES_LEGENDARY(311, "Assassin Shoes \u25C6\u25C6\u25C6", "Boosts Agility by 27%.", Rarity.LEGENDARY, 0),
    ESTER_SHOES_LEGENDARY(312, "Ester Shoes \u25C6\u25C6\u25C6", "Boosts Agility by 32%.", Rarity.LEGENDARY, 0),
    NACRE_CHOKER_LEGENDARY(313, "Nacre Choker \u25C6\u25C6\u25C6", "Boosts Luck by 22%.", Rarity.LEGENDARY, 3),
    GODDESS_CHOKER_LEGENDARY(314, "Goddess Choker \u25C6\u25C6\u25C6", "Boosts Luck by 27%.", Rarity.LEGENDARY, 3),
    COMET_CHOKER_LEGENDARY(315, "Comet Choker \u25C6\u25C6\u25C6", "Boosts Luck by 32%.", Rarity.LEGENDARY, 3),
    RIGID_VEST_LEGENDARY(316, "Rigid Vest \u25C6\u25C6\u25C6", "Increases maximum HP by 300.", Rarity.LEGENDARY, 2),
    INFANTRY_VEST_LEGENDARY(317, "Infantry Vest \u25C6\u25C6\u25C6", "Increases maximum HP by 500.", Rarity.LEGENDARY, 2),
    MUSCLE_BELT_LEGENDARY(318, "Muscle Belt \u25C6\u25C6\u25C6", "Increases Strength by 22.", Rarity.LEGENDARY, 4),
    CHAMPION_BELT_LEGENDARY(319, "Champion Belt \u25C6\u25C6\u25C6", "Increases Strength by 27.", Rarity.LEGENDARY, 4),
    FLUFFY_HAT_LEGENDARY(320, "Fluffy Hat \u25C6\u25C6\u25C6", "Increases Ether by 22.", Rarity.LEGENDARY, 1),
    FABULOUS_HAT_LEGENDARY(321, "Fabulous Hat \u25C6\u25C6\u25C6", "Increases Ether by 27.", Rarity.LEGENDARY, 1),
    LEATHER_GLOVES_LEGENDARY(322, "Leather Gloves \u25C6\u25C6\u25C6", "Increases Dexterity by 22.", Rarity.LEGENDARY, 6),
    SMITHY_GLOVES_LEGENDARY(323, "Smithy Gloves \u25C6\u25C6\u25C6", "Increases Dexterity by 27.", Rarity.LEGENDARY, 6),
    WOLF_SHOES_LEGENDARY(324, "Wolf Shoes \u25C6\u25C6\u25C6", "Increases Agility by 12.", Rarity.LEGENDARY, 0),
    SPRING_SHOES_LEGENDARY(325, "Spring Shoes \u25C6\u25C6\u25C6", "Increases Agility by 17.", Rarity.LEGENDARY, 0),
    BUNNIT_CHOKER_LEGENDARY(326, "Bunnit Choker \u25C6\u25C6\u25C6", "Increases Luck by 22.", Rarity.LEGENDARY, 3),
    GOLD_GEAR_CHOKER_LEGENDARY(327, "Gold Gear Choker \u25C6\u25C6\u25C6", "Increases Luck by 27.", Rarity.LEGENDARY, 3),
    GARNET_LEGENDARY(328, "Garnet \u25C6\u25C6\u25C6", "Restores 5% HP of damage dealt after a successful auto-attack.", Rarity.LEGENDARY, 8),
    SAPPHIRE_LEGENDARY(329, "Sapphire \u25C6\u25C6\u25C6", "Restores 7% HP of damage dealt after a successful auto-attack.", Rarity.LEGENDARY, 8),
    DIAMOND_LEGENDARY(330, "Diamond \u25C6\u25C6\u25C6", "Restores 9% HP of damage dealt after a successful auto-attack.", Rarity.LEGENDARY, 8),
    CLASSIC_MEDAL_LEGENDARY(331, "Classic Medal \u25C6\u25C6\u25C6", "Absorbs 12% of critical damage dealt as HP.", Rarity.LEGENDARY, 9),
    MODERN_MEDAL_LEGENDARY(332, "Modern Medal \u25C6\u25C6\u25C6", "Absorbs 17% of critical damage dealt as HP.", Rarity.LEGENDARY, 9),
    AVANT_GARDE_MEDAL_LEGENDARY(333, "Avant-Garde Medal \u25C6\u25C6\u25C6", "Absorbs 22% of critical damage dealt as HP.", Rarity.LEGENDARY, 9),
    IRON_HEADBAND_LEGENDARY(334, "Iron Headband \u25C6\u25C6\u25C6", "Increases critical damage by 30%.", Rarity.LEGENDARY, 1),
    ICE_HEADBAND_LEGENDARY(335, "Ice Headband \u25C6\u25C6\u25C6", "Increases critical damage by 40%.", Rarity.LEGENDARY, 1),
    OPTICAL_HEADBAND_LEGENDARY(336, "Optical Headband \u25C6\u25C6\u25C6", "Increases critical damage by 50%.", Rarity.LEGENDARY, 1),
    MOON_CUBE_LEGENDARY(337, "Moon Cube \u25C6\u25C6\u25C6", "Adds a 30% chance of attacking again after a successful auto-attack.", Rarity.LEGENDARY, 7),
    STAR_CUBE_LEGENDARY(338, "Star Cube \u25C6\u25C6\u25C6", "Adds a 45% chance of attacking again after a successful auto-attack.", Rarity.LEGENDARY, 7),
    GALAXY_CUBE_LEGENDARY(339, "Galaxy Cube \u25C6\u25C6\u25C6", "Adds a 60% chance of attacking again after a successful auto-attack.", Rarity.LEGENDARY, 7),
    MECHANIZED_GREAVES_LEGENDARY(340, "Mechanized Greaves \u25C6\u25C6\u25C6", "Increases damage dealt to toppled enemies by 60%.", Rarity.LEGENDARY, 0),
    CRYSTAL_GREAVES_LEGENDARY(341, "Crystal Greaves \u25C6\u25C6\u25C6", "Increases damage dealt to toppled enemies by 85%.", Rarity.LEGENDARY, 0),
    GRAPHITE_GREAVES_LEGENDARY(342, "Graphite Greaves \u25C6\u25C6\u25C6", "Increases damage dealt to toppled enemies by 110%.", Rarity.LEGENDARY, 0),
    SWORDFIGHTING_BANNER_LEGENDARY(343, "Swordfighting Banner \u25C6\u25C6\u25C6", "Increases damage dealt to launched enemies by 60%.", Rarity.LEGENDARY, 5),
    GODDESS_BANNER_LEGENDARY(344, "Goddess Banner \u25C6\u25C6\u25C6", "Increases damage dealt to launched enemies by 85%.", Rarity.LEGENDARY, 5),
    ANCIENT_BANNER_LEGENDARY(345, "Ancient Banner \u25C6\u25C6\u25C6", "Increases damage dealt to launched enemies by 110%.", Rarity.LEGENDARY, 5),
    SPIKED_PAULDRONS_LEGENDARY(346, "Spiked Pauldrons \u25C6\u25C6\u25C6", "Increases smash damage by 60%.", Rarity.LEGENDARY, 2),
    HERO_PAULDRONS_LEGENDARY(347, "Hero Pauldrons \u25C6\u25C6\u25C6", "Increases smash damage by 85%.", Rarity.LEGENDARY, 2),
    JET_PAULDRONS_LEGENDARY(348, "Jet Pauldrons \u25C6\u25C6\u25C6", "Increases smash damage by 110%.", Rarity.LEGENDARY, 2),
    APPRENTICE_VAMBRACES_LEGENDARY(349, "Apprentice Vambraces \u25C6\u25C6\u25C6", "Increases damage dealt to higher-level enemies by 30%.", Rarity.LEGENDARY, 6),
    BOXER_VAMBRACES_LEGENDARY(350, "Boxer Vambraces \u25C6\u25C6\u25C6", "Increases damage dealt to higher-level enemies by 45%.", Rarity.LEGENDARY, 6),
    HERO_VAMBRACES_LEGENDARY(351, "Hero Vambraces \u25C6\u25C6\u25C6", "Increases damage dealt to higher-level enemies by 60%.", Rarity.LEGENDARY, 6),
    DARK_ORB_LEGENDARY(352, "Dark Orb \u25C6\u25C6\u25C6", "Increases damage dealt when an ally is incapacitated by 60%.", Rarity.LEGENDARY, 8),
    ERASER_ORB_LEGENDARY(353, "Eraser Orb \u25C6\u25C6\u25C6", "Increases damage dealt when an ally is incapacitated by 110%.", Rarity.LEGENDARY, 8),
    BLOODY_ORB_LEGENDARY(354, "Bloody Orb \u25C6\u25C6\u25C6", "Increases damage dealt when an ally is incapacitated by 160%.", Rarity.LEGENDARY, 8),
    CHROME_SCARF_LEGENDARY(355, "Chrome Scarf \u25C6\u25C6\u25C6", "Extends Break duration by 19%.", Rarity.LEGENDARY, 3),
    UNICORN_SCARF_LEGENDARY(356, "Unicorn Scarf \u25C6\u25C6\u25C6", "Extends Break duration by 34%.", Rarity.LEGENDARY, 3),
    QUANTUM_SCARF_LEGENDARY(357, "Quantum Scarf \u25C6\u25C6\u25C6", "Extends Break duration by 49%.", Rarity.LEGENDARY, 3),
    WHITE_BELT_LEGENDARY(358, "White Belt \u25C6\u25C6\u25C6", "Extends Topple duration by 17%.", Rarity.LEGENDARY, 4),
    BLACK_BELT_LEGENDARY(359, "Black Belt \u25C6\u25C6\u25C6", "Extends Topple duration by 22%.", Rarity.LEGENDARY, 4),
    PLATINUM_BELT_LEGENDARY(360, "Platinum Belt \u25C6\u25C6\u25C6", "Extends Topple duration by 27%.", Rarity.LEGENDARY, 4),
    SOLDIER_RING_LEGENDARY(361, "Soldier Ring \u25C6\u25C6\u25C6", "Extends Launch duration by 17%.", Rarity.LEGENDARY, 8),
    BERSERK_RING_LEGENDARY(362, "Berserk Ring \u25C6\u25C6\u25C6", "Extends Launch duration by 22%.", Rarity.LEGENDARY, 8),
    TYRANT_RING_LEGENDARY(363, "Tyrant Ring \u25C6\u25C6\u25C6", "Extends Launch duration by 27%.", Rarity.LEGENDARY, 8),
    ATTACK_STONE_LEGENDARY(364, "Attack Stone \u25C6\u25C6\u25C6", "Increases auto-attack damage by 30%.", Rarity.LEGENDARY, 8),
    ASSAULT_STONE_LEGENDARY(365, "Assault Stone \u25C6\u25C6\u25C6", "Increases auto-attack damage by 50%.", Rarity.LEGENDARY, 8),
    BREAK_STONE_LEGENDARY(366, "Break Stone \u25C6\u25C6\u25C6", "Increases auto-attack damage by 70%.", Rarity.LEGENDARY, 8),
    WORLD_TREE_DROP_LEGENDARY(367, "World Tree Drop \u25C6\u25C6\u25C6", "Increases damage dealt per Blade Switch by 12% (max: 250%).", Rarity.LEGENDARY, 8),
    MALE_LOINCLOTH_LEGENDARY(368, "Male Loincloth \u25C6\u25C6\u25C6", "Increases damage dealt while Blade is the opposite gender by 60%.", Rarity.LEGENDARY, 5),
    CHARMING_SWIMSUIT_LEGENDARY(369, "Charming Swimsuit \u25C6\u25C6\u25C6", "Increases damage dealt while Blade is the opposite gender by 60%.", Rarity.LEGENDARY, 5),
    ALPHA_SCOPE_LEGENDARY(370, "Alpha Scope \u25C6\u25C6\u25C6", "Reduces enemy Topple resist.", Rarity.LEGENDARY, 1),
    GAMMA_SCOPE_LEGENDARY(371, "Gamma Scope \u25C6\u25C6\u25C6", "Reduces enemy Launch resist.", Rarity.LEGENDARY, 1),
    BEAST_HOOD_LEGENDARY(372, "Beast Hood \u25C6\u25C6\u25C6", "Increases aggro reduction by 22%.", Rarity.LEGENDARY, 1),
    CAMO_HOOD_LEGENDARY(373, "Camo Hood \u25C6\u25C6\u25C6", "Increases aggro reduction by 27%.", Rarity.LEGENDARY, 1),
    SKELETON_HOOD_LEGENDARY(374, "Skeleton Hood \u25C6\u25C6\u25C6", "Increases aggro reduction by 32%.", Rarity.LEGENDARY, 1),
    NOPON_MASK_LEGENDARY(375, "Nopon Mask \u25C6\u25C6\u25C6", "Increases aggro every second. (Minor effect.)", Rarity.LEGENDARY, 1),
    METAL_NOPON_MASK_LEGENDARY(376, "Metal Nopon Mask \u25C6\u25C6\u25C6", "Increases aggro every second. (Medium effect.)", Rarity.LEGENDARY, 1),
    GOLD_NOPON_MASK_LEGENDARY(377, "Gold Nopon Mask \u25C6\u25C6\u25C6", "Increases aggro every second. (Major effect.)", Rarity.LEGENDARY, 1),
    COLORFUL_FEATHER_LEGENDARY(378, "Colorful Feather \u25C6\u25C6\u25C6", "Start each battle with aggro. (Minor effect.)", Rarity.LEGENDARY, 9),
    SILVER_FEATHER_LEGENDARY(379, "Silver Feather \u25C6\u25C6\u25C6", "Start each battle with aggro. (Medium effect.)", Rarity.LEGENDARY, 9),
    PHANTOM_FEATHER_LEGENDARY(380, "Phantom Feather \u25C6\u25C6\u25C6", "Start each battle with aggro. (Major effect.)", Rarity.LEGENDARY, 9),
    GRANDARBOR_WARD_LEGENDARY(381, "Grandarbor Ward \u25C6\u25C6\u25C6", "Increases the HP restored when being revived by 29%.", Rarity.LEGENDARY, 9),
    SPIRIT_TREE_WARD_LEGENDARY(382, "Spirit Tree Ward \u25C6\u25C6\u25C6", "Increases the HP restored when being revived by 39%.", Rarity.LEGENDARY, 9),
    WORLD_TREE_WARD_LEGENDARY(383, "World Tree Ward \u25C6\u25C6\u25C6", "Increases the HP restored when being revived by 49%.", Rarity.LEGENDARY, 9),
    FRIENDSHIP_RING_LEGENDARY(384, "Friendship Ring \u25C6\u25C6\u25C6", "Increases the HP restored when reviving a teammate by 29%.", Rarity.LEGENDARY, 8),
    AFFECTION_RING_LEGENDARY(385, "Affection Ring \u25C6\u25C6\u25C6", "Increases the HP restored when reviving a teammate by 39%.", Rarity.LEGENDARY, 8),
    PROMISE_RING_LEGENDARY(386, "Promise Ring \u25C6\u25C6\u25C6", "Increases the HP restored when reviving a teammate by 49%.", Rarity.LEGENDARY, 8),
    HARVEST_NECKLACE_LEGENDARY(387, "Harvest Necklace \u25C6\u25C6\u25C6", "Improves the effect of Healing Arts by 14%.", Rarity.LEGENDARY, 3),
    AFFECTION_NECKLACE_LEGENDARY(388, "Affection Necklace \u25C6\u25C6\u25C6", "Improves the effect of Healing Arts by 19%.", Rarity.LEGENDARY, 3),
    HOLY_NECKLACE_LEGENDARY(389, "Holy Necklace \u25C6\u25C6\u25C6", "Improves the effect of Healing Arts by 24%.", Rarity.LEGENDARY, 3),
    SHELL_CAMEO_LEGENDARY(390, "Shell Cameo \u25C6\u25C6\u25C6", "Increases HP restored to self (not using HP Potions) by 14%.", Rarity.LEGENDARY, 9),
    CHIVALRIC_MEDAL_LEGENDARY(391, "Chivalric Medal \u25C6\u25C6\u25C6", "Restores 3.5% HP when canceling an auto-attack with a Driver Art.", Rarity.LEGENDARY, 9),
    MILITARY_MEDAL_LEGENDARY(392, "Military Medal \u25C6\u25C6\u25C6", "Restores 4.5% HP when canceling an auto-attack with a Driver Art.", Rarity.LEGENDARY, 9),
    ROUND_TABLE_MEDAL_LEGENDARY(393, "Round Table Medal \u25C6\u25C6\u25C6", "Restores 5.5% HP when canceling an auto-attack with a Driver Art.", Rarity.LEGENDARY, 9),
    GAUNTLET_LEGENDARY(394, "Gauntlet \u25C6\u25C6\u25C6", "Boosts recharge for Specials after canceling by 24%.", Rarity.LEGENDARY, 6),
    BIO_GAUNTLET_LEGENDARY(395, "Bio Gauntlet \u25C6\u25C6\u25C6", "Boosts recharge for Specials after canceling by 34%.", Rarity.LEGENDARY, 6),
    NANO_METAL_GAUNTLET_LEGENDARY(396, "Nano-Metal Gauntlet \u25C6\u25C6\u25C6", "Boosts recharge for Specials after canceling by 44%.", Rarity.LEGENDARY, 6),
    EYEPATCH_LEGENDARY(397, "Eyepatch \u25C6\u25C6\u25C6", "Adds 24% to damage ratio after canceling an auto-attack.", Rarity.LEGENDARY, 1),
    LEADERS_EYEPATCH_LEGENDARY(398, "Leader's Eyepatch \u25C6\u25C6\u25C6", "Adds 39% to damage ratio after canceling an auto-attack.", Rarity.LEGENDARY, 1),
    HI_TECH_EYEPATCH_LEGENDARY(399, "Hi-Tech Eyepatch \u25C6\u25C6\u25C6", "Adds 54% to damage ratio after canceling an auto-attack.", Rarity.LEGENDARY, 1),
    SILVER_EARRINGS_LEGENDARY(400, "Silver Earrings \u25C6\u25C6\u25C6", "Fills Party Gauge on \"Excellent\" Specials. (Minor effect.)", Rarity.LEGENDARY, 8),
    CRYSTAL_EARRINGS_LEGENDARY(401, "Crystal Earrings \u25C6\u25C6\u25C6", "Fills Party Gauge on \"Excellent\" Specials. (Major effect.)", Rarity.LEGENDARY, 8),
    OMEGA_DRIVE_LEGENDARY(402, "Omega Drive \u25C6\u25C6\u25C6", "Slightly fills the Party Gauge for each critical hit delivered.", Rarity.LEGENDARY, 7),
    SIGMA_DRIVE_LEGENDARY(403, "Sigma Drive \u25C6\u25C6\u25C6", "Slightly fills the Party Gauge for each Driver Art used.", Rarity.LEGENDARY, 7),
    BURST_SYMBOL_LEGENDARY(404, "Burst Symbol \u25C6\u25C6\u25C6", "Increases attack power ratio at the start of a Chain Attack.", Rarity.LEGENDARY, 9),
    CRITICAL_SYMBOL_LEGENDARY(405, "Critical Symbol \u25C6\u25C6\u25C6", "Increases critical hit rate during a Chain Attack by 54%.", Rarity.LEGENDARY, 9),
    RECOVERY_SYMBOL_LEGENDARY(406, "Recovery Symbol \u25C6\u25C6\u25C6", "Heals 60% HP each time a Chain Attack is initiated.", Rarity.LEGENDARY, 9),
    INFINITY_SYMBOL_LEGENDARY(407, "Infinity Symbol \u25C6\u25C6\u25C6", "Slightly fills the Party Gauge at the end of each Chain Attack.", Rarity.LEGENDARY, 9),
    SWORD_ATTACHMENT_LEGENDARY(408, "Sword Attachment \u25C6\u25C6\u25C6", "Increases attack power of Aegis Sword-class weapons by 29%.", Rarity.LEGENDARY, 7),
    SCIMITAR_ATTACHMENT_LEGENDARY(409, "Scimitar Attachment \u25C6\u25C6\u25C6", "Increases attack power of Catalyst Scimitar-class weapons by 29%.", Rarity.LEGENDARY, 7),
    RING_ATTACHMENT_LEGENDARY(410, "Ring Attachment \u25C6\u25C6\u25C6", "Increases attack power of Twin Rings-class weapons by 29%.", Rarity.LEGENDARY, 7),
    SHIELD_ATTACHMENT_LEGENDARY(411, "Shield Attachment \u25C6\u25C6\u25C6", "Increases attack power of Drill Shield-class weapons by 29%.", Rarity.LEGENDARY, 7),
    ARMS_ATTACHMENT_LEGENDARY(412, "Arms Attachment \u25C6\u25C6\u25C6", "Increases attack power of Mech Arms-class weapons by 29%.", Rarity.LEGENDARY, 7),
    SABER_ATTACHMENT_LEGENDARY(413, "Saber Attachment \u25C6\u25C6\u25C6", "Increases attack power of Variable Saber-class weapons by 29%.", Rarity.LEGENDARY, 7),
    WHIP_ATTACHMENT_LEGENDARY(414, "Whip Attachment \u25C6\u25C6\u25C6", "Increases attack power of Whipsword-class weapons by 29%.", Rarity.LEGENDARY, 7),
    EDGE_ATTACHMENT_LEGENDARY(415, "Edge Attachment \u25C6\u25C6\u25C6", "Increases attack power of Big Bang Edge-class weapons by 29%.", Rarity.LEGENDARY, 7),
    SCYTHE_ATTACHMENT_LEGENDARY(416, "Scythe Attachment \u25C6\u25C6\u25C6", "Increases attack power of Dual Scythes-class weapons by 29%.", Rarity.LEGENDARY, 7),
    AXE_ATTACHMENT_LEGENDARY(417, "Axe Attachment \u25C6\u25C6\u25C6", "Increases attack power of Greataxe-class weapons by 29%.", Rarity.LEGENDARY, 7),
    LANCE_ATTACHMENT_LEGENDARY(418, "Lance Attachment \u25C6\u25C6\u25C6", "Increases attack power of Megalance-class weapons by 29%.", Rarity.LEGENDARY, 7),
    CANNON_ATTACHMENT_LEGENDARY(419, "Cannon Attachment \u25C6\u25C6\u25C6", "Increases attack power of Ether Cannon-class weapons by 29%.", Rarity.LEGENDARY, 7),
    HAMMER_ATTACHMENT_LEGENDARY(420, "Hammer Attachment \u25C6\u25C6\u25C6", "Increases attack power of Shield Hammer-class weapons by 29%.", Rarity.LEGENDARY, 7),
    KATANA_ATTACHMENT_LEGENDARY(421, "Katana Attachment \u25C6\u25C6\u25C6", "Increases attack power of Chroma Katana-class weapons by 29%.", Rarity.LEGENDARY, 7),
    BALL_ATTACHMENT_LEGENDARY(422, "Ball Attachment \u25C6\u25C6\u25C6", "Increases attack power of Bitball-class weapons by 29%.", Rarity.LEGENDARY, 7),
    KNUCKLE_ATTACHMENT_LEGENDARY(423, "Knuckle Attachment \u25C6\u25C6\u25C6", "Increases attack power of Knuckle Claws-class weapons by 29%.", Rarity.LEGENDARY, 7),
    MASTER_ATTACHMENT_LEGENDARY(424, "Master Attachment \u25C6\u25C6\u25C6", "Increases the attack power of all weapon classes by 14%.", Rarity.LEGENDARY, 7),
    CHEER_TREAT_LEGENDARY(425, "Cheer Treat \u25C6\u25C6\u25C6", "Increases Affinity by 60% after winning a Special button challenge.", Rarity.LEGENDARY, 5),
    RED_THREAD_LEGENDARY(426, "Red Thread \u25C6\u25C6\u25C6", "Extends the range of Driver-Blade Affinity by 120cm.", Rarity.LEGENDARY, 5),
    LOVE_THREAD_LEGENDARY(427, "Love Thread \u25C6\u25C6\u25C6", "Extends the range of Driver-Blade Affinity by 170cm.", Rarity.LEGENDARY, 5),
    PASSION_THREAD_LEGENDARY(428, "Passion Thread \u25C6\u25C6\u25C6", "Extends the range of Driver-Blade Affinity by 220cm.", Rarity.LEGENDARY, 5),
    ACTIVITY_AMULET_LEGENDARY(429, "Activity Amulet \u25C6\u25C6\u25C6", "Boosts the effect of HP Potions by 24%.", Rarity.LEGENDARY, 8),
    HEALING_AMULET_LEGENDARY(430, "Healing Amulet \u25C6\u25C6\u25C6", "Boosts the effect of HP Potions by 34%.", Rarity.LEGENDARY, 8),
    REBIRTH_AMULET_LEGENDARY(431, "Rebirth Amulet \u25C6\u25C6\u25C6", "Boosts the effect of HP Potions by 44%.", Rarity.LEGENDARY, 8),
    BETA_SCOPE_LEGENDARY(432, "Beta Scope \u25C6\u25C6\u25C6", "Reduces enemy Break resist.", Rarity.LEGENDARY, 1),
    RUSH_HOUR_LEGENDARY(433, "Rush Hour \u25C6\u25C6\u25C6", "Expands the window of opportunity for canceling by 70%.", Rarity.LEGENDARY, 7),
    APPEALING_LAMP_LEGENDARY(434, "Appealing Lamp \u25C6\u25C6\u25C6", "Adds 35% buffer time to combos if switching to a combo-requesting Blade.", Rarity.LEGENDARY, 5),
    OVERCLOCKING_BANGLE_LEGENDARY(435, "Overclocking Bangle \u25C6\u25C6\u25C6", "Shortens cooldown time relative to the no. of Arts ready after a Blade Switch.", Rarity.LEGENDARY, 6),
    MINT_POTPOURRI_LEGENDARY(436, "Mint Potpourri \u25C6\u25C6\u25C6", "Boosts taunt resistance by 70%.", Rarity.LEGENDARY, 5),
    LAVENDER_POTPOURRI_LEGENDARY(437, "Lavender Potpourri \u25C6\u25C6\u25C6", "Boosts taunt resistance by 100%.", Rarity.LEGENDARY, 5),
    PRIESTESSS_AUSPICES_LEGENDARY(438, "Priestess's Auspices \u25C6\u25C6\u25C6", "Boosts Driver shackle resistance by 70%.", Rarity.LEGENDARY, 3),
    SAGES_AUSPICES_LEGENDARY(439, "Sage's Auspices \u25C6\u25C6\u25C6", "Boosts Driver shackle resistance by 100%.", Rarity.LEGENDARY, 3),
    INCENSE_OF_CALM_LEGENDARY(440, "Incense of Calm \u25C6\u25C6\u25C6", "Increases resistance to Stench by 70%.", Rarity.LEGENDARY, 5),
    INCENSE_OF_INSIGHT_LEGENDARY(441, "Incense of Insight \u25C6\u25C6\u25C6", "Increases resistance to Stench by 100%.", Rarity.LEGENDARY, 5),
    NOPON_DOLL_COMMON(442, "Nopon Doll \u25C6", "When a Driver is incapacitated, 50% of aggro is retained.", Rarity.COMMON, 5),
    AVIAN_TOTEM_CARVING_LEGENDARY(443, "Avian Totem Carving \u25C6\u25C6\u25C6", "Restores 5.5% HP of damage dealt after a successful auto-attack.", Rarity.LEGENDARY, 5),
    CONSUL_GREAVES_COMMON(456, "Consul Greaves \u25C6", "Increases movement speed in combat by 25%.", Rarity.COMMON, 0),
    CONSUL_GREAVES_RARE(457, "Consul Greaves \u25C6\u25C6", "Increases movement speed in combat by 30%.", Rarity.RARE, 0),
    CONSUL_GREAVES_LEGENDARY(458, "Consul Greaves \u25C6\u25C6\u25C6", "Increases movement speed in combat by 35%.", Rarity.LEGENDARY, 0),
    INFINITY_GREAVES_COMMON(459, "Infinity Greaves \u25C6", "Increases movement speed in combat by 50%.", Rarity.COMMON, 0),
    INFINITY_GREAVES_RARE(460, "Infinity Greaves \u25C6\u25C6", "Increases movement speed in combat by 55%.", Rarity.RARE, 0),
    INFINITY_GREAVES_LEGENDARY(461, "Infinity Greaves \u25C6\u25C6\u25C6", "Increases movement speed in combat by 60%.", Rarity.LEGENDARY, 0),
    NIGHT_VISION_KIT_COMMON(462, "Night-vision Kit \u25C6", "Increases item drop collection range by 100cm.", Rarity.COMMON, 1),
    NIGHT_VISION_KIT_RARE(463, "Night-vision Kit \u25C6\u25C6", "Increases item drop collection range by 105cm.", Rarity.RARE, 1),
    NIGHT_VISION_KIT_LEGENDARY(464, "Night-vision Kit \u25C6\u25C6\u25C6", "Increases item drop collection range by 110cm.", Rarity.LEGENDARY, 1),
    AUGMENTED_VISION_KIT_COMMON(465, "Augmented Vision Kit \u25C6", "Increases item drop collection range by 200cm.", Rarity.COMMON, 1),
    AUGMENTED_VISION_KIT_RARE(466, "Augmented Vision Kit \u25C6\u25C6", "Increases item drop collection range by 205cm.", Rarity.RARE, 1),
    AUGMENTED_VISION_KIT_LEGENDARY(467, "Augmented Vision Kit \u25C6\u25C6\u25C6", "Increases item drop collection range by 210cm.", Rarity.LEGENDARY, 1),
    CHARM_BANGLE_COMMON(468, "Charm Bangle \u25C6", "Boosts Nullify Heal resistance by 60%.", Rarity.COMMON, 6),
    CHARM_BANGLE_RARE(469, "Charm Bangle \u25C6\u25C6", "Boosts Nullify Heal resistance by 65%.", Rarity.RARE, 6),
    CHARM_BANGLE_LEGENDARY(470, "Charm Bangle \u25C6\u25C6\u25C6", "Boosts Nullify Heal resistance by 70%.", Rarity.LEGENDARY, 6),
    BELEMNITE_BANGLE_COMMON(471, "Belemnite Bangle \u25C6", "Boosts Nullify Heal resistance by 90%.", Rarity.COMMON, 6),
    BELEMNITE_BANGLE_RARE(472, "Belemnite Bangle \u25C6\u25C6", "Boosts Nullify Heal resistance by 95%.", Rarity.RARE, 6),
    BELEMNITE_BANGLE_LEGENDARY(473, "Belemnite Bangle \u25C6\u25C6\u25C6", "Boosts Nullify Heal resistance by 100%.", Rarity.LEGENDARY, 6),
    SEVEN_LEAGUE_CIRCLET_COMMON(474, "Seven-League Circlet \u25C6", "Boosts Doom resistance by 60%.", Rarity.COMMON, 1),
    SEVEN_LEAGUE_CIRCLET_RARE(475, "Seven-League Circlet \u25C6\u25C6", "Boosts Doom resistance by 65%.", Rarity.RARE, 1),
    SEVEN_LEAGUE_CIRCLET_LEGENDARY(476, "Seven-League Circlet \u25C6\u25C6\u25C6", "Boosts Doom resistance by 70%.", Rarity.LEGENDARY, 1),
    FIGHTERS_CIRCLET_COMMON(477, "Fighter's Circlet \u25C6", "Boosts Doom resistance by 90%.", Rarity.COMMON, 1),
    FIGHTERS_CIRCLET_RARE(478, "Fighter's Circlet \u25C6\u25C6", "Boosts Doom resistance by 95%.", Rarity.RARE, 1),
    FIGHTERS_CIRCLET_LEGENDARY(479, "Fighter's Circlet \u25C6\u25C6\u25C6", "Boosts Doom resistance by 100%.", Rarity.LEGENDARY, 1),
    OCEAN_EARRING_COMMON(480, "Ocean Earring \u25C6", "Boosts resistance to Party-Gauge- draining attacks by 60%.", Rarity.COMMON, 8),
    OCEAN_EARRING_RARE(481, "Ocean Earring \u25C6\u25C6", "Boosts resistance to Party-Gauge- draining attacks by 65%.", Rarity.RARE, 8),
    OCEAN_EARRING_LEGENDARY(482, "Ocean Earring \u25C6\u25C6\u25C6", "Boosts resistance to Party-Gauge- draining attacks by 70%.", Rarity.LEGENDARY, 8),
    SEVEN_SEAS_EARRING_COMMON(483, "Seven-Seas Earring \u25C6", "Boosts resistance to Party-Gauge- draining attacks by 90%.", Rarity.COMMON, 8),
    SEVEN_SEAS_EARRING_RARE(484, "Seven-Seas Earring \u25C6\u25C6", "Boosts resistance to Party-Gauge- draining attacks by 95%.", Rarity.RARE, 8),
    SEVEN_SEAS_EARRING_LEGENDARY(485, "Seven-Seas Earring \u25C6\u25C6\u25C6", "Boosts resistance to Party-Gauge- draining attacks by 100%.", Rarity.LEGENDARY, 8),
    TERROR_MASQUE_COMMON(486, "Terror Masque \u25C6", "Deal 50% more and take 25% more damage.", Rarity.COMMON, 1),
    TERROR_MASQUE_RARE(487, "Terror Masque \u25C6\u25C6", "Deal 55% more and take 27% more damage.", Rarity.RARE, 1),
    TERROR_MASQUE_LEGENDARY(488, "Terror Masque \u25C6\u25C6\u25C6", "Deal 60% more and take 30% more damage.", Rarity.LEGENDARY, 1),
    ABYSS_MASQUE_COMMON(489, "Abyss Masque \u25C6", "Deal 100% more and take 50% more damage.", Rarity.COMMON, 1),
    ABYSS_MASQUE_RARE(490, "Abyss Masque \u25C6\u25C6", "Deal 105% more and take 52% more damage.", Rarity.RARE, 1),
    ABYSS_MASQUE_LEGENDARY(491, "Abyss Masque \u25C6\u25C6\u25C6", "Deal 110% more and take 55% more damage.", Rarity.LEGENDARY, 1),
    ENVOYS_FOOTGEAR_COMMON(492, "Envoy's Footgear \u25C6", "Take 15% less and deal 30% less damage.", Rarity.COMMON, 0),
    ENVOYS_FOOTGEAR_RARE(493, "Envoy's Footgear \u25C6\u25C6", "Take 17% less and deal 35% less damage.", Rarity.RARE, 0),
    ENVOYS_FOOTGEAR_LEGENDARY(494, "Envoy's Footgear \u25C6\u25C6\u25C6", "Take 20% less and deal 40% less damage.", Rarity.LEGENDARY, 0),
    SURVIVORS_FOOTGEAR_COMMON(495, "Survivor's Footgear \u25C6", "Take 25% less and deal 50% less damage.", Rarity.COMMON, 0),
    SURVIVORS_FOOTGEAR_RARE(496, "Survivor's Footgear \u25C6\u25C6", "Take 27% less and deal 55% less damage.", Rarity.RARE, 0),
    SURVIVORS_FOOTGEAR_LEGENDARY(497, "Survivor's Footgear \u25C6\u25C6\u25C6", "Take 30% less and deal 60% less damage.", Rarity.LEGENDARY, 0),
    TWIN_TRUNKS_VEST_COMMON(498, "Twin Trunks Vest \u25C6", "Boosts maximum HP by 35%.", Rarity.COMMON, 2),
    TWIN_TRUNKS_VEST_RARE(499, "Twin Trunks Vest \u25C6\u25C6", "Boosts maximum HP by 36%.", Rarity.RARE, 2),
    TWIN_TRUNKS_VEST_LEGENDARY(500, "Twin Trunks Vest \u25C6\u25C6\u25C6", "Boosts maximum HP by 37%.", Rarity.LEGENDARY, 2),
    BEAST_HIDE_VEST_COMMON(501, "Beast-Hide Vest \u25C6", "Boosts Strength by 35%.", Rarity.COMMON, 4),
    BEAST_HIDE_VEST_RARE(502, "Beast-Hide Vest \u25C6\u25C6", "Boosts Strength by 36%.", Rarity.RARE, 4),
    BEAST_HIDE_VEST_LEGENDARY(503, "Beast-Hide Vest \u25C6\u25C6\u25C6", "Boosts Strength by 37%.", Rarity.LEGENDARY, 4),
    PRAIRIE_CAP_COMMON(504, "Prairie Cap \u25C6", "Boosts Ether by 35%.", Rarity.COMMON, 1),
    PRAIRIE_CAP_RARE(505, "Prairie Cap \u25C6\u25C6", "Boosts Ether by 36%.", Rarity.RARE, 1),
    PRAIRIE_CAP_LEGENDARY(506, "Prairie Cap \u25C6\u25C6\u25C6", "Boosts Ether by 37%.", Rarity.LEGENDARY, 1),
    VIVID_MITTS_COMMON(507, "Vivid Mitts \u25C6", "Boosts Dexterity by 35%.", Rarity.COMMON, 6),
    VIVID_MITTS_RARE(508, "Vivid Mitts \u25C6\u25C6", "Boosts Dexterity by 36%.", Rarity.RARE, 6),
    VIVID_MITTS_LEGENDARY(509, "Vivid Mitts \u25C6\u25C6\u25C6", "Boosts Dexterity by 37%.", Rarity.LEGENDARY, 6),
    DAUNTLESS_BOOTS_COMMON(510, "Dauntless Boots \u25C6", "Boosts Agility by 35%.", Rarity.COMMON, 0),
    DAUNTLESS_BOOTS_RARE(511, "Dauntless Boots \u25C6\u25C6", "Boosts Agility by 36%.", Rarity.RARE, 0),
    DAUNTLESS_BOOTS_LEGENDARY(512, "Dauntless Boots \u25C6\u25C6\u25C6", "Boosts Agility by 37%.", Rarity.LEGENDARY, 0),
    SUNLIGHT_CHOKER_COMMON(513, "Sunlight Choker \u25C6", "Boosts Luck by 35%.", Rarity.COMMON, 3),
    SUNLIGHT_CHOKER_RARE(514, "Sunlight Choker \u25C6\u25C6", "Boosts Luck by 36%.", Rarity.RARE, 3),
    SUNLIGHT_CHOKER_LEGENDARY(515, "Sunlight Choker \u25C6\u25C6\u25C6", "Boosts Luck by 37%.", Rarity.LEGENDARY, 3),
    ALEXANDRITE_COMMON(516, "Alexandrite \u25C6", "Restores 10% HP of damage dealt after a successful auto-attack.", Rarity.COMMON, 8),
    ALEXANDRITE_RARE(517, "Alexandrite \u25C6\u25C6", "Restores 10.5% HP of damage dealt after a successful auto-attack.", Rarity.RARE, 8),
    ALEXANDRITE_LEGENDARY(518, "Alexandrite \u25C6\u25C6\u25C6", "Restores 11% HP of damage dealt after a successful auto-attack.", Rarity.LEGENDARY, 8),
    CRIMSON_HEADBAND_COMMON(519, "Crimson Headband \u25C6", "Increases critical damage by 50%.", Rarity.COMMON, 1),
    CRIMSON_HEADBAND_RARE(520, "Crimson Headband \u25C6\u25C6", "Increases critical damage by 55%.", Rarity.RARE, 1),
    CRIMSON_HEADBAND_LEGENDARY(521, "Crimson Headband \u25C6\u25C6\u25C6", "Increases critical damage by 60%.", Rarity.LEGENDARY, 1),
    BLACK_CUBE_COMMON(522, "Black Cube \u25C6", "Adds a 65% chance of attacking again after a successful auto-attack.", Rarity.COMMON, 7),
    BLACK_CUBE_RARE(523, "Black Cube \u25C6\u25C6", "Adds a 70% chance of attacking again after a successful auto-attack.", Rarity.RARE, 7),
    BLACK_CUBE_LEGENDARY(524, "Black Cube \u25C6\u25C6\u25C6", "Adds a 75% chance of attacking again after a successful auto-attack.", Rarity.LEGENDARY, 7),
    STAUNCH_BOOTS_COMMON(525, "Staunch Boots \u25C6", "Increases damage dealt to toppled enemies by 125%.", Rarity.COMMON, 0),
    STAUNCH_BOOTS_RARE(526, "Staunch Boots \u25C6\u25C6", "Increases damage dealt to toppled enemies by 130%.", Rarity.RARE, 0),
    STAUNCH_BOOTS_LEGENDARY(527, "Staunch Boots \u25C6\u25C6\u25C6", "Increases damage dealt to toppled enemies by 135%.", Rarity.LEGENDARY, 0),
    WAR_GOD_BANNER_COMMON(528, "War God Banner \u25C6", "Increases damage dealt to launched enemies by 125%.", Rarity.COMMON, 5),
    WAR_GOD_BANNER_RARE(529, "War God Banner \u25C6\u25C6", "Increases damage dealt to launched enemies by 130%.", Rarity.RARE, 5),
    WAR_GOD_BANNER_LEGENDARY(530, "War God Banner \u25C6\u25C6\u25C6", "Increases damage dealt to launched enemies by 135%.", Rarity.LEGENDARY, 5),
    CONSUL_PAULDRONS_COMMON(531, "Consul Pauldrons \u25C6", "Increases smash damage by 125%.", Rarity.COMMON, 2),
    CONSUL_PAULDRONS_RARE(532, "Consul Pauldrons \u25C6\u25C6", "Increases smash damage by 130%.", Rarity.RARE, 2),
    CONSUL_PAULDRONS_LEGENDARY(533, "Consul Pauldrons \u25C6\u25C6\u25C6", "Increases smash damage by 135%.", Rarity.LEGENDARY, 2),
    DIVINE_VAMBRACES_COMMON(534, "Divine Vambraces \u25C6", "Increases damage dealt to higher-level enemies by 65%.", Rarity.COMMON, 6),
    DIVINE_VAMBRACES_RARE(535, "Divine Vambraces \u25C6\u25C6", "Increases damage dealt to higher-level enemies by 70%.", Rarity.RARE, 6),
    DIVINE_VAMBRACES_LEGENDARY(536, "Divine Vambraces \u25C6\u25C6\u25C6", "Increases damage dealt to higher-level enemies by 75%.", Rarity.LEGENDARY, 6),
    DEMON_ORB_COMMON(537, "Demon Orb \u25C6", "Increases damage dealt when an ally is incapacitated by 200%.", Rarity.COMMON, 8),
    DEMON_ORB_RARE(538, "Demon Orb \u25C6\u25C6", "Increases damage dealt when an ally is incapacitated by 205%.", Rarity.RARE, 8),
    DEMON_ORB_LEGENDARY(539, "Demon Orb \u25C6\u25C6\u25C6", "Increases damage dealt when an ally is incapacitated by 210%.", Rarity.LEGENDARY, 8),
    TACHYON_SCARF_COMMON(540, "Tachyon Scarf \u25C6", "Extends Break duration by 60%.", Rarity.COMMON, 3),
    TACHYON_SCARF_RARE(541, "Tachyon Scarf \u25C6\u25C6", "Extends Break duration by 62%.", Rarity.RARE, 3),
    TACHYON_SCARF_LEGENDARY(542, "Tachyon Scarf \u25C6\u25C6\u25C6", "Extends Break duration by 64%.", Rarity.LEGENDARY, 3),
    RAINBOW_BELT_COMMON(543, "Rainbow Belt \u25C6", "Extends Topple duration by 30%.", Rarity.COMMON, 4),
    RAINBOW_BELT_RARE(544, "Rainbow Belt \u25C6\u25C6", "Extends Topple duration by 31%.", Rarity.RARE, 4),
    RAINBOW_BELT_LEGENDARY(545, "Rainbow Belt \u25C6\u25C6\u25C6", "Extends Topple duration by 32%.", Rarity.LEGENDARY, 4),
    GOLIATH_RING_COMMON(546, "Goliath Ring \u25C6", "Extends Launch duration by 30%.", Rarity.COMMON, 8),
    GOLIATH_RING_RARE(547, "Goliath Ring \u25C6\u25C6", "Extends Launch duration by 31%.", Rarity.RARE, 8),
    GOLIATH_RING_LEGENDARY(548, "Goliath Ring \u25C6\u25C6\u25C6", "Extends Launch duration by 32%.", Rarity.LEGENDARY, 8),
    VIOLENT_STONE_COMMON(549, "Violent Stone \u25C6", "Increases auto-attack damage by 80%.", Rarity.COMMON, 8),
    VIOLENT_STONE_RARE(550, "Violent Stone \u25C6\u25C6", "Increases auto-attack damage by 85%.", Rarity.RARE, 8),
    VIOLENT_STONE_LEGENDARY(551, "Violent Stone \u25C6\u25C6\u25C6", "Increases auto-attack damage by 90%.", Rarity.LEGENDARY, 8),
    ENLIGHTENED_LOINCLOTH_COMMON(552, "Enlightened Loincloth \u25C6", "Increases damage dealt while Blade is the opposite gender by 75%.", Rarity.COMMON, 5),
    ENLIGHTENED_LOINCLOTH_RARE(553, "Enlightened Loincloth \u25C6\u25C6", "Increases damage dealt while Blade is the opposite gender by 80%.", Rarity.RARE, 5),
    ENLIGHTENED_LOINCLOTH_LEGENDARY(554, "Enlightened Loincloth \u25C6\u25C6\u25C6", "Increases damage dealt while Blade is the opposite gender by 85%.", Rarity.LEGENDARY, 5),
    GLAMOROUS_SWIMSUIT_COMMON(555, "Glamorous Swimsuit \u25C6", "Increases damage dealt while Blade is the opposite gender by 75%.", Rarity.COMMON, 5),
    GLAMOROUS_SWIMSUIT_RARE(556, "Glamorous Swimsuit \u25C6\u25C6", "Increases damage dealt while Blade is the opposite gender by 80%.", Rarity.RARE, 5),
    GLAMOROUS_SWIMSUIT_LEGENDARY(557, "Glamorous Swimsuit \u25C6\u25C6\u25C6", "Increases damage dealt while Blade is the opposite gender by 85%.", Rarity.LEGENDARY, 5),
    VANISH_HOOD_COMMON(558, "Vanish Hood \u25C6", "Increases aggro reduction by 35%.", Rarity.COMMON, 1),
    VANISH_HOOD_RARE(559, "Vanish Hood \u25C6\u25C6", "Increases aggro reduction by 36%.", Rarity.RARE, 1),
    VANISH_HOOD_LEGENDARY(560, "Vanish Hood \u25C6\u25C6\u25C6", "Increases aggro reduction by 37%.", Rarity.LEGENDARY, 1),
    PLATINUM_NOPON_MASK_COMMON(561, "Platinum Nopon Mask \u25C6", "Increases aggro every second. (Extra-major effect.)", Rarity.COMMON, 1),
    PLATINUM_NOPON_MASK_RARE(562, "Platinum Nopon Mask \u25C6\u25C6", "Increases aggro every second. (Extra-major effect.)", Rarity.RARE, 1),
    PLATINUM_NOPON_MASK_LEGENDARY(563, "Platinum Nopon Mask \u25C6\u25C6\u25C6", "Increases aggro every second. (Extra-major effect.)", Rarity.LEGENDARY, 1),
    GARGANTUAN_FEATHER_COMMON(564, "Gargantuan Feather \u25C6", "Start each battle with aggro. (Extra-major effect.)", Rarity.COMMON, 9),
    GARGANTUAN_FEATHER_RARE(565, "Gargantuan Feather \u25C6\u25C6", "Start each battle with aggro. (Extra-major effect.)", Rarity.RARE, 9),
    GARGANTUAN_FEATHER_LEGENDARY(566, "Gargantuan Feather \u25C6\u25C6\u25C6", "Start each battle with aggro. (Extra-major effect.)", Rarity.LEGENDARY, 9),
    SAINTS_NECKLACE_COMMON(567, "Saint's Necklace \u25C6", "Improves the effect of Healing Arts by 25%.", Rarity.COMMON, 3),
    SAINTS_NECKLACE_RARE(568, "Saint's Necklace \u25C6\u25C6", "Improves the effect of Healing Arts by 27%.", Rarity.RARE, 3),
    SAINTS_NECKLACE_LEGENDARY(569, "Saint's Necklace \u25C6\u25C6\u25C6", "Improves the effect of Healing Arts by 29%.", Rarity.LEGENDARY, 3),
    MARBLE_CAMEO_COMMON(570, "Marble Cameo \u25C6", "Increases HP restored to self (not using HP Potions) by 20%.", Rarity.COMMON, 9),
    MARBLE_CAMEO_RARE(571, "Marble Cameo \u25C6\u25C6", "Increases HP restored to self (not using HP Potions) by 22%.", Rarity.RARE, 9),
    MARBLE_CAMEO_LEGENDARY(572, "Marble Cameo \u25C6\u25C6\u25C6", "Increases HP restored to self (not using HP Potions) by 24%.", Rarity.LEGENDARY, 9),
    BEATIFIC_MEDAL_COMMON(573, "Beatific Medal \u25C6", "Restores 6% HP when canceling an auto-attack with a Driver Art.", Rarity.COMMON, 9),
    BEATIFIC_MEDAL_RARE(574, "Beatific Medal \u25C6\u25C6", "Restores 6.2% HP when canceling an auto-attack with a Driver Art.", Rarity.RARE, 9),
    BEATIFIC_MEDAL_LEGENDARY(575, "Beatific Medal \u25C6\u25C6\u25C6", "Restores 6.5% HP when canceling an auto-attack with a Driver Art.", Rarity.LEGENDARY, 9),
    CARBON_GAUNTLET_COMMON(576, "Carbon Gauntlet \u25C6", "Boosts recharge for Specials after canceling by 50%.", Rarity.COMMON, 6),
    CARBON_GAUNTLET_RARE(577, "Carbon Gauntlet \u25C6\u25C6", "Boosts recharge for Specials after canceling by 52%.", Rarity.RARE, 6),
    CARBON_GAUNTLET_LEGENDARY(578, "Carbon Gauntlet \u25C6\u25C6\u25C6", "Boosts recharge for Specials after canceling by 54%.", Rarity.LEGENDARY, 6),
    NOISE_DAMPENER_COMMON(579, "Noise Dampener \u25C6", "Adds 65% to damage ratio after canceling an auto-attack.", Rarity.COMMON, 1),
    NOISE_DAMPENER_RARE(580, "Noise Dampener \u25C6\u25C6", "Adds 67% to damage ratio after canceling an auto-attack.", Rarity.RARE, 1),
    NOISE_DAMPENER_LEGENDARY(581, "Noise Dampener \u25C6\u25C6\u25C6", "Adds 69% to damage ratio after canceling an auto-attack.", Rarity.LEGENDARY, 1),
    MASTER_SCOPE_COMMON(582, "Master Scope \u25C6", "Reduces enemy Break resist.", Rarity.COMMON, 1),
    MASTER_SCOPE_RARE(583, "Master Scope \u25C6\u25C6", "Reduces enemy Break resist.", Rarity.RARE, 1),
    MASTER_SCOPE_LEGENDARY(584, "Master Scope \u25C6\u25C6\u25C6", "Reduces enemy Break resist.", Rarity.LEGENDARY, 1),
    PROTOTYPE_SUIT_REX_LEGENDARY(648, "Prototype Suit Rex \u25C6\u25C6\u25C6", "Adds a 60% chance of attacking again after a successful auto-attack.", Rarity.LEGENDARY, 2),
    CANDY_STRIPE_NIA_LEGENDARY(649, "Candy Stripe Nia \u25C6\u25C6\u25C6", "Improves the effect of Healing Arts by 24%.", Rarity.LEGENDARY, 2),
    BUSTER_MODE_TORA_LEGENDARY(650, "Buster-Mode Tora \u25C6\u25C6\u25C6", "Restores 9% HP of damage dealt after a successful auto-attack.", Rarity.LEGENDARY, 2),
    DRESS_UNIFORM_MORAG_LEGENDARY(651, "Dress Uniform Mòrag \u25C6\u25C6\u25C6", "Boosts Dexterity by 32%.", Rarity.LEGENDARY, 2),
    EMBERCAKE_ZEKE_LEGENDARY(652, "Embercake Zeke \u25C6\u25C6\u25C6", "Increases critical damage by 50%.", Rarity.LEGENDARY, 2);


    private int id;
    private String name, description;
    private Rarity rarity;
    private Image icon;

    Accessory(int id, String name, String description, Rarity rarity, int icon) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.rarity = rarity;
        switch(icon) {
            case 0: this.icon = Image.SHOES; break;
            case 1: this.icon = Image.HAT; break;
            case 2: this.icon = Image.VEST; break;
            case 3: this.icon = Image.CHOCKER; break;
            case 4: this.icon = Image.BELT; break;
            case 5: this.icon = Image.BANNER; break;
            case 6: this.icon = Image.GLOVES; break;
            case 7: this.icon = Image.CUBE; break;
            case 8: this.icon = Image.ORB; break;
            case 9: this.icon = Image.MEDAL; break;
        }
    }

    public int getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public String getDescription() {
        return description;
    }

    public Rarity getRarity() {
        return rarity;
    }

    public Image getIcon() {
        return icon;
    }

    public static Accessory fromId(short id) {
        for (Accessory item:values()) {
            if(id == (short)(item.id & 0xFFFF))
                return item;
        }
        return null;
    }

    public static Accessory fromName(String name) {
        for (Accessory item:values()) {
            if(name.equalsIgnoreCase(item.name))
                return item;
        }
        return null;
    }

    public static String[] stringValues() {
        ArrayList<String> strValues = new ArrayList<>();
        for(Accessory item:values()) {
            strValues.add(item.getName());
        }
        return strValues.toArray(new String[0]);
    }
}
