package me.notanullpointer.xc2editor.save;

import java.util.ArrayList;

public enum PouchItem {

    JUICY_SAMOD(1, "Juicy Samod", PouchCategory.STAPLE_FOODS, Rarity.COMMON, PouchEffect.fromId(1), 20),
    LIGHTLY_FRIED_RICE(2, "Lightly Fried Rice", PouchCategory.STAPLE_FOODS, Rarity.COMMON, PouchEffect.fromId(2), 20),
    ARGENTUM_NOODLE_SOUP(3, "Argentum Noodle Soup", PouchCategory.STAPLE_FOODS, Rarity.RARE, PouchEffect.fromId(3), 20),
    MASSIVE_MUSHROOM_PIE(4, "Massive Mushroom Pie", PouchCategory.STAPLE_FOODS, Rarity.RARE, PouchEffect.fromId(4), 20),
    BRIGHT_SAMOD(5, "Bright Samod", PouchCategory.STAPLE_FOODS, Rarity.RARE, PouchEffect.fromId(5), 40),
    TASTY_KORDETH_SAMOD(6, "Tasty Kordeth Samod", PouchCategory.STAPLE_FOODS, Rarity.RARE, PouchEffect.fromId(6), 70),
    GRILLED_ANCHORTAIL(7, "Grilled Anchortail", PouchCategory.SEAFOOD, Rarity.COMMON, PouchEffect.fromId(7), 20),
    OYSTER_STIR_FRY(8, "Oyster Stir-Fry", PouchCategory.SEAFOOD, Rarity.RARE, PouchEffect.fromId(8), 20),
    MARINE_STIR_FRY(9, "Marine Stir-Fry", PouchCategory.SEAFOOD, Rarity.RARE, PouchEffect.fromId(9), 60),
    MELODIOUS_MELON_PARFAIT(10, "Melodious Melon Parfait", PouchCategory.DESSERTS, Rarity.COMMON, PouchEffect.fromId(10), 20),
    CINNOPON_ROLL(11, "Cinnopon Roll", PouchCategory.DESSERTS, Rarity.COMMON, PouchEffect.fromId(11), 20),
    SPARKLESUGAR(12, "Sparklesugar", PouchCategory.DESSERTS, Rarity.RARE, PouchEffect.fromId(12), 20),
    FRUITY_RICE_BALL(13, "Fruity Rice Ball", PouchCategory.DESSERTS, Rarity.RARE, PouchEffect.fromId(13), 30),
    NARCIPEAR_JELLY(14, "Narcipear Jelly", PouchCategory.DESSERTS, Rarity.LEGENDARY, PouchEffect.fromId(14), 70),
    TWINKLEJUICE(15, "Twinklejuice", PouchCategory.DRINKS, Rarity.COMMON, PouchEffect.fromId(15), 20),
    FIZZ_JUICE(16, "Fizz Juice", PouchCategory.DRINKS, Rarity.COMMON, PouchEffect.fromId(16), 20),
    CHUNKY_JUICE(17, "Chunky Juice", PouchCategory.DRINKS, Rarity.COMMON, PouchEffect.fromId(17), 20),
    SAPPAN_VEG_JUICE(18, "Sappan Veg Juice", PouchCategory.DRINKS, Rarity.RARE, PouchEffect.fromId(18), 30),
    HONEY_AU_LAIT(19, "Honey au Lait", PouchCategory.DRINKS, Rarity.RARE, PouchEffect.fromId(19), 40),
    CRISPY_BLENDSHAKE(20, "Crispy Blendshake", PouchCategory.DRINKS, Rarity.LEGENDARY, PouchEffect.fromId(20), 50),
    ROLY_POLY_MARACAS(21, "Roly-Poly Maracas", PouchCategory.INSTRUMENTS, Rarity.COMMON, PouchEffect.fromId(21), 120),
    NOPOLELE(22, "Nopolele", PouchCategory.INSTRUMENTS, Rarity.COMMON, PouchEffect.fromId(22), 120),
    FUNKY_CONGA(23, "Funky Conga", PouchCategory.INSTRUMENTS, Rarity.COMMON, PouchEffect.fromId(23), 120),
    WHISPERCORDER(24, "Whispercorder", PouchCategory.INSTRUMENTS, Rarity.RARE, PouchEffect.fromId(24), 120),
    CASTA_MUTES(25, "Casta-Mutes", PouchCategory.INSTRUMENTS, Rarity.RARE, PouchEffect.fromId(25), 192),
    CLICKY_CLACKS(26, "Clicky-Clacks", PouchCategory.INSTRUMENTS, Rarity.LEGENDARY, PouchEffect.fromId(26), 240),
    SALVAGING_MADE_EASY(27, "Salvaging Made Easy", PouchCategory.LITERATURE, Rarity.COMMON, PouchEffect.fromId(27), 120),
    YUMYUMS_GOLDEN_GUN(28, "Yumyum's Golden Gun", PouchCategory.LITERATURE, Rarity.COMMON, PouchEffect.fromId(28), 120),
    THE_MILLENARIAN_TITAN(29, "The Millenarian Titan", PouchCategory.LITERATURE, Rarity.RARE, PouchEffect.fromId(29), 120),
    ADVENTURES_OF_MYRAM(30, "Adventures of Myram", PouchCategory.LITERATURE, Rarity.RARE, PouchEffect.fromId(30), 144),
    MUMUNI_THE_LITTLEPON(31, "Mumuni the Littlepon", PouchCategory.LITERATURE, Rarity.LEGENDARY, PouchEffect.fromId(31), 192),
    CLATTERTONGUE(32, "Clattertongue", PouchCategory.BOARD_GAMES, Rarity.COMMON, PouchEffect.fromId(32), 120),
    NOPON_CHESS_SET(33, "Nopon Chess Set", PouchCategory.BOARD_GAMES, Rarity.COMMON, PouchEffect.fromId(33), 120),
    SNEAK_THIEF_KING(34, "Sneak-Thief King", PouchCategory.BOARD_GAMES, Rarity.COMMON, PouchEffect.fromId(34), 120),
    TRADEWAY_66(35, "Tradeway 66", PouchCategory.BOARD_GAMES, Rarity.RARE, PouchEffect.fromId(35), 120),
    CORAL_NOPON_CHESS_SET(36, "Coral Nopon Chess Set", PouchCategory.BOARD_GAMES, Rarity.RARE, PouchEffect.fromId(36), 168),
    LEFTHERIAN_LIFE(37, "Leftherian Life", PouchCategory.BOARD_GAMES, Rarity.LEGENDARY, PouchEffect.fromId(37), 216),
    EAU_DE_DOUX(38, "Eau de Doux", PouchCategory.COSMETICS, Rarity.RARE, PouchEffect.fromId(38), 120),
    ELASTIFYING_TONIC(39, "Elastifying Tonic", PouchCategory.COSMETICS, Rarity.RARE, PouchEffect.fromId(39), 120),
    FRESHENING_GEL(40, "Freshening Gel", PouchCategory.COSMETICS, Rarity.RARE, PouchEffect.fromId(40), 120),
    CURLED_EYELASHES(41, "Curled Eyelashes", PouchCategory.COSMETICS, Rarity.RARE, PouchEffect.fromId(41), 120),
    BUBBLY_MANI_PEDI_KIT(42, "Bubbly Mani-Pedi Kit", PouchCategory.COSMETICS, Rarity.RARE, PouchEffect.fromId(42), 168),
    FULL_MOON_EYELINER(43, "Full Moon Eyeliner", PouchCategory.COSMETICS, Rarity.LEGENDARY, PouchEffect.fromId(43), 216),
    RUSKA_DUMPLINGS(44, "Ruska Dumplings", PouchCategory.STAPLE_FOODS, Rarity.COMMON, PouchEffect.fromId(44), 20),
    RUSKA_NOODLE_GOULASH(45, "Ruska Noodle Goulash", PouchCategory.STAPLE_FOODS, Rarity.COMMON, PouchEffect.fromId(45), 20),
    DELUXE_HAM_TOASTIE(46, "Deluxe Ham Toastie", PouchCategory.STAPLE_FOODS, Rarity.COMMON, PouchEffect.fromId(46), 20),
    RUSKA_NOODLE_SOUP(47, "Ruska Noodle Soup", PouchCategory.STAPLE_FOODS, Rarity.RARE, PouchEffect.fromId(47), 30),
    BEAT_PASTE_PARATHA(48, "Beat Paste Paratha", PouchCategory.STAPLE_FOODS, Rarity.LEGENDARY, PouchEffect.fromId(48), 50),
    CRISPY_SAUTE(49, "Crispy Sauté", PouchCategory.VEGETABLES, Rarity.COMMON, PouchEffect.fromId(49), 20),
    TORIGOTH_MARINADE(50, "Torigoth Marinade", PouchCategory.VEGETABLES, Rarity.COMMON, PouchEffect.fromId(50), 20),
    STUFFED_MEATY_CARROT(51, "Stuffed Meaty Carrot", PouchCategory.VEGETABLES, Rarity.COMMON, PouchEffect.fromId(51), 20),
    PURI_LEAF_SALAD(52, "Puri Leaf Salad", PouchCategory.VEGETABLES, Rarity.RARE, PouchEffect.fromId(52), 30),
    SNOWY_DUDLEYA_GELEE(53, "Snowy Dudleya Gelée", PouchCategory.VEGETABLES, Rarity.LEGENDARY, PouchEffect.fromId(53), 70),
    ESTRAL_STEAK(54, "Estral Steak", PouchCategory.MEAT, Rarity.COMMON, PouchEffect.fromId(54), 20),
    TASTY_SAUSAGE(55, "Tasty Sausage", PouchCategory.MEAT, Rarity.COMMON, PouchEffect.fromId(55), 20),
    MINCE_AND_LENTIL_STIR_FRY(56, "Mince & Lentil Stir-Fry", PouchCategory.MEAT, Rarity.RARE, PouchEffect.fromId(56), 40),
    MUSTARD_KORDETH(57, "Mustard Kordeth", PouchCategory.MEAT, Rarity.LEGENDARY, PouchEffect.fromId(57), 70),
    GORMOTTI_FISH_FLAKES(58, "Gormotti Fish Flakes", PouchCategory.SEAFOOD, Rarity.COMMON, PouchEffect.fromId(58), 20),
    GRASS_SMOKED_SALMON(59, "Grass-Smoked Salmon", PouchCategory.SEAFOOD, Rarity.RARE, PouchEffect.fromId(59), 20),
    BIPEDAL_CRAB_CHILI(60, "Bipedal Crab Chili", PouchCategory.SEAFOOD, Rarity.LEGENDARY, PouchEffect.fromId(60), 60),
    LUNANA_SMOOTHIE(61, "Lunana Smoothie", PouchCategory.DRINKS, Rarity.COMMON, PouchEffect.fromId(61), 20),
    GORMOTTI_HONEYTEA(62, "Gormotti Honeytea", PouchCategory.DRINKS, Rarity.COMMON, PouchEffect.fromId(62), 20),
    KUKUREL_SPRINGWATER(63, "Kukurel Springwater", PouchCategory.DRINKS, Rarity.COMMON, PouchEffect.fromId(63), 20),
    PASSION_FRUIT_SHAKE(64, "Passion Fruit Shake", PouchCategory.DRINKS, Rarity.RARE, PouchEffect.fromId(64), 40),
    VICTORY_SMOOTHIE(65, "Victory Smoothie", PouchCategory.DRINKS, Rarity.LEGENDARY, PouchEffect.fromId(65), 60),
    TORIGONDA(66, "Torigonda", PouchCategory.INSTRUMENTS, Rarity.COMMON, PouchEffect.fromId(66), 120),
    WOODGRAIN_ALPHORN(67, "Woodgrain Alphorn", PouchCategory.INSTRUMENTS, Rarity.COMMON, PouchEffect.fromId(67), 120),
    CEDARWOOD_KOTO(68, "Cedarwood Koto", PouchCategory.INSTRUMENTS, Rarity.COMMON, PouchEffect.fromId(68), 120),
    WOODBOARD(69, "Woodboard", PouchCategory.INSTRUMENTS, Rarity.RARE, PouchEffect.fromId(69), 168),
    CORALLINE_MARIMBA(70, "Coralline Marimba", PouchCategory.INSTRUMENTS, Rarity.LEGENDARY, PouchEffect.fromId(70), 216),
    THE_GIRL_ON_THE_HILL(71, "The Girl on the Hill", PouchCategory.ART, Rarity.COMMON, PouchEffect.fromId(71), 120),
    BLACK_FLOWER_FIELD(72, "Black Flower Field", PouchCategory.ART, Rarity.COMMON, PouchEffect.fromId(72), 120),
    WOODCUT_PRINT_OF_BANA(73, "Woodcut Print of Bana", PouchCategory.ART, Rarity.RARE, PouchEffect.fromId(73), 144),
    WOOD_CARVEN_QUEEN(74, "Wood-Carven Queen", PouchCategory.ART, Rarity.LEGENDARY, PouchEffect.fromId(74), 216),
    PUFFOUNDATION(75, "Puffoundation", PouchCategory.COSMETICS, Rarity.COMMON, PouchEffect.fromId(75), 120),
    TREESAP_CONDITIONER(76, "Treesap Conditioner", PouchCategory.COSMETICS, Rarity.COMMON, PouchEffect.fromId(76), 120),
    FLURRYCOMB(77, "Flurrycomb", PouchCategory.COSMETICS, Rarity.COMMON, PouchEffect.fromId(77), 120),
    CONCH_HAIRPIN(78, "Conch Hairpin", PouchCategory.COSMETICS, Rarity.RARE, PouchEffect.fromId(78), 192),
    SPARKLY_SNOW_PERFUME(79, "Sparkly Snow Perfume", PouchCategory.COSMETICS, Rarity.LEGENDARY, PouchEffect.fromId(79), 240),
    PUZZLETREE_POUCH(80, "Puzzletree Pouch", PouchCategory.TEXTILES, Rarity.COMMON, PouchEffect.fromId(80), 120),
    TORIGOTH_WEAVE_MAT(81, "Torigoth-Weave Mat", PouchCategory.TEXTILES, Rarity.COMMON, PouchEffect.fromId(81), 120),
    WOOD_DYE_WAISTCLOTH(82, "Wood-Dye Waistcloth", PouchCategory.TEXTILES, Rarity.COMMON, PouchEffect.fromId(82), 120),
    SUN_DAPPLED_CURTAINS(83, "Sun-Dappled Curtains", PouchCategory.TEXTILES, Rarity.RARE, PouchEffect.fromId(83), 120),
    LEAF_WEAVE_CAPE(84, "Leaf-Weave Cape", PouchCategory.TEXTILES, Rarity.RARE, PouchEffect.fromId(84), 192),
    SNOWFLAKE_SCARF(85, "Snowflake Scarf", PouchCategory.TEXTILES, Rarity.LEGENDARY, PouchEffect.fromId(85), 240),
    WRAPPED_GLARNA_BAKE(86, "Wrapped Glarna Bake", PouchCategory.STAPLE_FOODS, Rarity.COMMON, PouchEffect.fromId(86), 20),
    THREE_CHEESE_PURAN(87, "Three-Cheese Puran", PouchCategory.STAPLE_FOODS, Rarity.COMMON, PouchEffect.fromId(87), 20),
    GLITTERSPUD_PURAN(88, "Glitterspud Puran", PouchCategory.STAPLE_FOODS, Rarity.RARE, PouchEffect.fromId(88), 30),
    HEARTY_KORDETH_PURAN(89, "Hearty Kordeth Puran", PouchCategory.STAPLE_FOODS, Rarity.LEGENDARY, PouchEffect.fromId(89), 60),
    POMEGRANATE_SOUP(90, "Pomegranate Soup", PouchCategory.VEGETABLES, Rarity.COMMON, PouchEffect.fromId(90), 20),
    SOUR_SPARK_ON_A_STICK(91, "Sour-Spark-on-a-Stick", PouchCategory.VEGETABLES, Rarity.COMMON, PouchEffect.fromId(91), 20),
    BOILED_HUSTLE_HYACINTH(92, "Boiled Hustle Hyacinth", PouchCategory.VEGETABLES, Rarity.RARE, PouchEffect.fromId(92), 40),
    PICKLED_ICE_CABBAGE(93, "Pickled Ice Cabbage", PouchCategory.VEGETABLES, Rarity.LEGENDARY, PouchEffect.fromId(93), 60),
    ARMU_T_BONE_STEAK(94, "Armu T-Bone Steak", PouchCategory.MEAT, Rarity.COMMON, PouchEffect.fromId(94), 20),
    MIXED_MEAT_PLATTER(95, "Mixed Meat Platter", PouchCategory.MEAT, Rarity.COMMON, PouchEffect.fromId(95), 20),
    HOTPLATE_FRY_UP(96, "Hotplate Fry-Up", PouchCategory.MEAT, Rarity.RARE, PouchEffect.fromId(96), 40),
    CHAR_GRILLED_GRUMBIRD(97, "Char-Grilled Grumbird", PouchCategory.MEAT, Rarity.LEGENDARY, PouchEffect.fromId(97), 70),
    DRIED_SUNFISH(98, "Dried Sunfish", PouchCategory.SEAFOOD, Rarity.COMMON, PouchEffect.fromId(98), 20),
    BULLYBELLY_CARPACCIO(99, "Bullybelly Carpaccio", PouchCategory.SEAFOOD, Rarity.COMMON, PouchEffect.fromId(99), 20),
    STEAMED_BLUEGILL(100, "Steamed Bluegill", PouchCategory.SEAFOOD, Rarity.RARE, PouchEffect.fromId(100), 30),
    WHITEBAIT_WITH_SEEDS(101, "Whitebait With Seeds", PouchCategory.SEAFOOD, Rarity.LEGENDARY, PouchEffect.fromId(101), 60),
    RAINBOW_PARFAIT(102, "Rainbow Parfait", PouchCategory.DESSERTS, Rarity.COMMON, PouchEffect.fromId(102), 20),
    BLOSSOM_CUSTARD(103, "Blossom Custard", PouchCategory.DESSERTS, Rarity.RARE, PouchEffect.fromId(103), 20),
    PLUMAGE_PEACH_JELLY(104, "Plumage Peach Jelly", PouchCategory.DESSERTS, Rarity.LEGENDARY, PouchEffect.fromId(104), 50),
    CHAMPS_CHURROS(105, "Champ's Churros", PouchCategory.DESSERTS, Rarity.COMMON, PouchEffect.fromId(105), 20),
    SNIPE_FLAN(108, "Snipe Flan", PouchCategory.DESSERTS, Rarity.RARE, PouchEffect.fromId(108), 20),
    CHERRY_CHEESE_MOUSSE(109, "Cherry Cheese Mousse", PouchCategory.DESSERTS, Rarity.LEGENDARY, PouchEffect.fromId(109), 40),
    NEON_GRAPE_FLAN(110, "Neon Grape Flan", PouchCategory.DESSERTS, Rarity.LEGENDARY, PouchEffect.fromId(110), 50),
    BLACK_ROAST_COFFEE(111, "Black Roast Coffee", PouchCategory.DRINKS, Rarity.COMMON, PouchEffect.fromId(111), 20),
    JENEROSSI_TEA(112, "Jenerossi Tea", PouchCategory.DRINKS, Rarity.COMMON, PouchEffect.fromId(112), 20),
    FIZZY_LASSI(113, "Fizzy Lassi", PouchCategory.DRINKS, Rarity.RARE, PouchEffect.fromId(113), 30),
    LENTIL_MILKSHAKE(114, "Lentil Milkshake", PouchCategory.DRINKS, Rarity.LEGENDARY, PouchEffect.fromId(114), 70),
    SCARLET_SHAMISEN(115, "Scarlet Shamisen", PouchCategory.INSTRUMENTS, Rarity.COMMON, PouchEffect.fromId(115), 120),
    FONSAN_VIOLA(116, "Fonsan Viola", PouchCategory.INSTRUMENTS, Rarity.COMMON, PouchEffect.fromId(116), 120),
    HEROS_HARP(117, "Hero's Harp", PouchCategory.INSTRUMENTS, Rarity.RARE, PouchEffect.fromId(117), 120),
    RUMBLE_CELLO(118, "Rumble Cello", PouchCategory.INSTRUMENTS, Rarity.RARE, PouchEffect.fromId(118), 144),
    CLOUDSNAIL_ARPEGGIONE(119, "Cloudsnail Arpeggione", PouchCategory.INSTRUMENTS, Rarity.LEGENDARY, PouchEffect.fromId(119), 192),
    PATRON_KINGS_CARVING(120, "Patron King's Carving", PouchCategory.ART, Rarity.COMMON, PouchEffect.fromId(120), 120),
    FINAL_CHORUS(121, "Final Chorus", PouchCategory.ART, Rarity.COMMON, PouchEffect.fromId(121), 120),
    SINGING_MAIDEN_STATUE(122, "Singing Maiden Statue", PouchCategory.ART, Rarity.RARE, PouchEffect.fromId(122), 192),
    SKYWARDS_BY_TITAN(123, "Skywards by Titan", PouchCategory.ART, Rarity.LEGENDARY, PouchEffect.fromId(123), 240),
    THE_ALRESTOGONY(124, "The Alrestogony", PouchCategory.LITERATURE, Rarity.COMMON, PouchEffect.fromId(124), 120),
    THE_LEGACY_OF_SELOSIA(125, "The Legacy of Selosia", PouchCategory.LITERATURE, Rarity.COMMON, PouchEffect.fromId(125), 120),
    MASTERPIECES_OF_ALREST(126, "Masterpieces of Alrest", PouchCategory.LITERATURE, Rarity.RARE, PouchEffect.fromId(126), 168),
    ADDAMS_LOVE_AND_WAR(127, "Addam's Love and War", PouchCategory.LITERATURE, Rarity.LEGENDARY, PouchEffect.fromId(127), 216),
    CASTLE_POKER(128, "Castle Poker", PouchCategory.BOARD_GAMES, Rarity.COMMON, PouchEffect.fromId(128), 120),
    GLADIATOR_WRESTLING(129, "Gladiator Wrestling", PouchCategory.BOARD_GAMES, Rarity.COMMON, PouchEffect.fromId(129), 120),
    CORAL_REVERSI(130, "Coral Reversi", PouchCategory.BOARD_GAMES, Rarity.COMMON, PouchEffect.fromId(130), 120),
    DUEL_LINE(131, "Duel Line", PouchCategory.BOARD_GAMES, Rarity.RARE, PouchEffect.fromId(131), 120),
    NOPOPO_YARD(132, "Nopopo Yard", PouchCategory.BOARD_GAMES, Rarity.RARE, PouchEffect.fromId(132), 144),
    CORAL_CASINO(133, "Coral Casino", PouchCategory.BOARD_GAMES, Rarity.LEGENDARY, PouchEffect.fromId(133), 240),
    RED_OPAL_LIPSTICK(134, "Red Opal Lipstick", PouchCategory.COSMETICS, Rarity.COMMON, PouchEffect.fromId(134), 120),
    TITAN_OIL_HAND_CREAM(135, "Titan-Oil Hand Cream", PouchCategory.COSMETICS, Rarity.COMMON, PouchEffect.fromId(135), 120),
    GOLDEN_MASCARA(136, "Golden Mascara", PouchCategory.COSMETICS, Rarity.COMMON, PouchEffect.fromId(136), 120),
    GORGEOUS_BLUSHER(137, "Gorgeous Blusher", PouchCategory.COSMETICS, Rarity.RARE, PouchEffect.fromId(137), 144),
    FONSETT_ROUGE_LIPGLOSS(138, "Fonsett-Rouge Lipgloss", PouchCategory.COSMETICS, Rarity.LEGENDARY, PouchEffect.fromId(138), 192),
    SANAR_KNIT_HEADBAND(139, "Sanar-Knit Headband", PouchCategory.TEXTILES, Rarity.COMMON, PouchEffect.fromId(139), 120),
    ARMU_SKIN_GLADIATOR(140, "Armu-Skin Gladiator", PouchCategory.TEXTILES, Rarity.COMMON, PouchEffect.fromId(140), 120),
    CORALWEAVE_TOWEL(141, "Coralweave Towel", PouchCategory.TEXTILES, Rarity.COMMON, PouchEffect.fromId(141), 120),
    DAZZLING_HANDKERCHIEF(142, "Dazzling Handkerchief", PouchCategory.TEXTILES, Rarity.RARE, PouchEffect.fromId(142), 120),
    GORMOTTI_WOODWING(143, "Gormotti Woodwing", PouchCategory.TEXTILES, Rarity.RARE, PouchEffect.fromId(143), 168),
    SANAR_KNIT_BLANKET(144, "Sanar-Knit Blanket", PouchCategory.TEXTILES, Rarity.LEGENDARY, PouchEffect.fromId(144), 216),
    DOLPHIN_CARROT_SLIDERS(145, "Dolphin Carrot Sliders", PouchCategory.VEGETABLES, Rarity.COMMON, PouchEffect.fromId(145), 20),
    CAMPFIRE_SKEWERS(146, "Campfire Skewers", PouchCategory.VEGETABLES, Rarity.COMMON, PouchEffect.fromId(146), 20),
    CRISPY_VEGETABLE_SALAD(147, "Crispy Vegetable Salad", PouchCategory.VEGETABLES, Rarity.RARE, PouchEffect.fromId(147), 30),
    STEAMFLAKE_TABBOULEH(148, "Steamflake Tabbouleh", PouchCategory.VEGETABLES, Rarity.LEGENDARY, PouchEffect.fromId(148), 60),
    MEAT_AND_LENTIL_SKEWER(149, "Meat & Lentil Skewer", PouchCategory.MEAT, Rarity.COMMON, PouchEffect.fromId(149), 20),
    HERBAL_TARTARE_KASCHA(150, "Herbal Tartare Kascha", PouchCategory.MEAT, Rarity.COMMON, PouchEffect.fromId(150), 20),
    GRUMBIRD_CASSEROLE(151, "Grumbird Casserole", PouchCategory.MEAT, Rarity.COMMON, PouchEffect.fromId(151), 20),
    ESTRAL_QUOTELETTAS(152, "Estral Quotelettas", PouchCategory.MEAT, Rarity.RARE, PouchEffect.fromId(152), 30),
    ARMU_AND_BEAN_STEW(153, "Armu & Bean Stew", PouchCategory.MEAT, Rarity.LEGENDARY, PouchEffect.fromId(153), 50),
    GRILLED_SALMON_IN_HERBS(154, "Grilled Salmon in Herbs", PouchCategory.SEAFOOD, Rarity.COMMON, PouchEffect.fromId(154), 20),
    CLOUD_SEA_CRAB_STICKS(155, "Cloud Sea Crab Sticks", PouchCategory.SEAFOOD, Rarity.COMMON, PouchEffect.fromId(155), 20),
    SAND_SALMON_CEVICHE(156, "Sand Salmon Ceviche", PouchCategory.SEAFOOD, Rarity.RARE, PouchEffect.fromId(156), 40),
    FISH_AND_HERB_BROTH(157, "Fish and Herb Broth", PouchCategory.SEAFOOD, Rarity.LEGENDARY, PouchEffect.fromId(157), 70),
    STEAMED_MILK_BRIOCHE(158, "Steamed Milk Brioche", PouchCategory.DESSERTS, Rarity.COMMON, PouchEffect.fromId(158), 20),
    STEAM_GEL_ICE_CREAM(159, "Steam-Gel Ice Cream", PouchCategory.DESSERTS, Rarity.COMMON, PouchEffect.fromId(159), 20),
    SWEET_LENTIL_BUN(160, "Sweet Lentil Bun", PouchCategory.DESSERTS, Rarity.COMMON, PouchEffect.fromId(160), 20),
    SKY_JEWEL_TART(161, "Sky-Jewel Tart", PouchCategory.DESSERTS, Rarity.RARE, PouchEffect.fromId(161), 20),
    ODIFA_GELEE_TART(162, "Odifa Gelée Tart", PouchCategory.DESSERTS, Rarity.RARE, PouchEffect.fromId(162), 50),
    HOT_RUBY_STEAMED_BUN(163, "Hot Ruby Steamed Bun", PouchCategory.DESSERTS, Rarity.LEGENDARY, PouchEffect.fromId(163), 70),
    PIPE_TRUMPET(164, "Pipe Trumpet", PouchCategory.INSTRUMENTS, Rarity.COMMON, PouchEffect.fromId(164), 120),
    STEAMWORK_ORGAN(165, "Steamwork Organ", PouchCategory.INSTRUMENTS, Rarity.COMMON, PouchEffect.fromId(165), 120),
    ARMY_ISSUE_VIOLIN(166, "Army-Issue Violin", PouchCategory.INSTRUMENTS, Rarity.COMMON, PouchEffect.fromId(166), 120),
    HAMMERPLATE_SNARE(167, "Hammerplate Snare", PouchCategory.INSTRUMENTS, Rarity.RARE, PouchEffect.fromId(167), 120),
    TUBE_XYLOPHONE(168, "Tube Xylophone", PouchCategory.INSTRUMENTS, Rarity.RARE, PouchEffect.fromId(168), 144),
    ICICLE_MARIMBA(169, "Icicle Marimba", PouchCategory.INSTRUMENTS, Rarity.LEGENDARY, PouchEffect.fromId(169), 216),
    PUNK_DOLL(170, "Punk Doll", PouchCategory.ART, Rarity.COMMON, PouchEffect.fromId(170), 120),
    COPPER_EPHEM_STATUE(171, "Copper Ephem Statue", PouchCategory.ART, Rarity.COMMON, PouchEffect.fromId(171), 120),
    FELMERI_FAIRY_STATUE(172, "Felmeri Fairy Statue", PouchCategory.ART, Rarity.RARE, PouchEffect.fromId(172), 144),
    CONCH_MUSIC_BOX(173, "Conch Music Box", PouchCategory.ART, Rarity.LEGENDARY, PouchEffect.fromId(173), 192),
    ARDAINIAN_ARMS_ALBUM(174, "Ardainian Arms Album", PouchCategory.LITERATURE, Rarity.COMMON, PouchEffect.fromId(174), 120),
    EMPEROR_EPHEMS_WAR(175, "Emperor Ephem's War", PouchCategory.LITERATURE, Rarity.COMMON, PouchEffect.fromId(175), 120),
    IMPERIAL_SECRET_ESCAPES(176, "Imperial Secret Escapes", PouchCategory.LITERATURE, Rarity.COMMON, PouchEffect.fromId(176), 120),
    LES_AWFULS(177, "Les Awfuls", PouchCategory.LITERATURE, Rarity.RARE, PouchEffect.fromId(177), 120),
    HOW_WARS_PROFIT_NOPON(178, "How Wars Profit Nopon", PouchCategory.LITERATURE, Rarity.RARE, PouchEffect.fromId(178), 168),
    LOVE_BEYOND_THE_CLOUDS(179, "Love Beyond the Clouds", PouchCategory.LITERATURE, Rarity.LEGENDARY, PouchEffect.fromId(179), 216),
    ARMY_FIELD_MANUAL(180, "Army Field Manual", PouchCategory.BOARD_GAMES, Rarity.COMMON, PouchEffect.fromId(180), 120),
    CHOOBY_TUBES(181, "Chooby Tubes", PouchCategory.BOARD_GAMES, Rarity.COMMON, PouchEffect.fromId(181), 120),
    SECRET_TRIALS(182, "Secret Trials", PouchCategory.BOARD_GAMES, Rarity.COMMON, PouchEffect.fromId(182), 120),
    DUELING_KINGDOMS(183, "Dueling Kingdoms", PouchCategory.BOARD_GAMES, Rarity.RARE, PouchEffect.fromId(183), 120),
    DEALING_KINGDOMS(184, "Dealing Kingdoms", PouchCategory.BOARD_GAMES, Rarity.RARE, PouchEffect.fromId(184), 168),
    PLUMBER_ESCAPE_GAME(185, "Plumber Escape Game", PouchCategory.BOARD_GAMES, Rarity.LEGENDARY, PouchEffect.fromId(185), 240),
    LYBARIAN_CHOWDER(186, "Lybarian Chowder", PouchCategory.VEGETABLES, Rarity.COMMON, PouchEffect.fromId(186), 20),
    GREEN_CHEESE_SALAD(187, "Green Cheese Salad", PouchCategory.VEGETABLES, Rarity.COMMON, PouchEffect.fromId(187), 20),
    VEGETABLE_MILLE_FEUILLE(188, "Vegetable Mille-Feuille", PouchCategory.VEGETABLES, Rarity.COMMON, PouchEffect.fromId(188), 20),
    VEG_AND_OYSTER_ASPIC(189, "Veg & Oyster Aspic", PouchCategory.VEGETABLES, Rarity.RARE, PouchEffect.fromId(189), 30),
    SNOWBABY_POTATO_SALAD(190, "Snowbaby Potato Salad", PouchCategory.VEGETABLES, Rarity.LEGENDARY, PouchEffect.fromId(190), 70),
    PASTEL_CAMILL(191, "Pastel Camill", PouchCategory.MEAT, Rarity.COMMON, PouchEffect.fromId(191), 20),
    ALBACON_FRYSTACK(192, "Albacon Frystack", PouchCategory.MEAT, Rarity.COMMON, PouchEffect.fromId(192), 20),
    SWEET_ARMU_BELLY_STEW(193, "Sweet Armu Belly Stew", PouchCategory.MEAT, Rarity.COMMON, PouchEffect.fromId(193), 20),
    ZAPROAST_POWER_BOWL(194, "Zaproast Power Bowl", PouchCategory.MEAT, Rarity.RARE, PouchEffect.fromId(194), 20),
    FRAGRANT_SAMOD_STRALU(195, "Fragrant Samod Stralu", PouchCategory.MEAT, Rarity.RARE, PouchEffect.fromId(195), 30),
    GLARNA_STIR_FRY(196, "Glarna Stir-Fry", PouchCategory.MEAT, Rarity.LEGENDARY, PouchEffect.fromId(196), 50),
    BROILED_PINFIN(197, "Broiled Pinfin", PouchCategory.SEAFOOD, Rarity.COMMON, PouchEffect.fromId(197), 20),
    SAUTEED_BEAT_SHRIMPS(198, "Sautéed Beat Shrimps", PouchCategory.SEAFOOD, Rarity.COMMON, PouchEffect.fromId(198), 20),
    BRAISED_CLOUD_SEA_SHARK(199, "Braised Cloud Sea Shark", PouchCategory.SEAFOOD, Rarity.COMMON, PouchEffect.fromId(199), 20),
    SMOKE_BRAISED_KILLIFISH(200, "Smoke-Braised Killifish", PouchCategory.SEAFOOD, Rarity.RARE, PouchEffect.fromId(200), 40),
    SEARED_WHITEBAIT(201, "Seared Whitebait", PouchCategory.SEAFOOD, Rarity.LEGENDARY, PouchEffect.fromId(201), 70),
    ODIFA(202, "Odifa", PouchCategory.DRINKS, Rarity.COMMON, PouchEffect.fromId(202), 20),
    INDOLINE_TEA(203, "Indoline Tea", PouchCategory.DRINKS, Rarity.COMMON, PouchEffect.fromId(203), 20),
    FROZEN_ODIFA(204, "Frozen Odifa", PouchCategory.DRINKS, Rarity.COMMON, PouchEffect.fromId(204), 20),
    PIPESTRAW_SMOOTHIE(205, "Pipestraw Smoothie", PouchCategory.DRINKS, Rarity.RARE, PouchEffect.fromId(205), 40),
    ARMU_MILK_EARL_GREY(206, "Armu Milk Earl Grey", PouchCategory.DRINKS, Rarity.LEGENDARY, PouchEffect.fromId(206), 60),
    LUNA_LIZARD_WREATH(207, "Luna Lizard Wreath", PouchCategory.ART, Rarity.COMMON, PouchEffect.fromId(207), 120),
    MONTECORAN_DOLL(208, "Montecoran Doll", PouchCategory.ART, Rarity.COMMON, PouchEffect.fromId(208), 120),
    STEEL_PIPE_LEXOS(209, "Steel Pipe Lexos", PouchCategory.ART, Rarity.RARE, PouchEffect.fromId(209), 168),
    LUSH_MOONBEAM_MASK(210, "Lush Moonbeam Mask", PouchCategory.ART, Rarity.LEGENDARY, PouchEffect.fromId(210), 216),
    JELLYFISH_BALSAM_RUG(211, "Jellyfish Balsam Rug", PouchCategory.TEXTILES, Rarity.COMMON, PouchEffect.fromId(211), 120),
    CODWEAVE_SHOP_CURTAIN(212, "Codweave Shop Curtain", PouchCategory.TEXTILES, Rarity.COMMON, PouchEffect.fromId(212), 120),
    CODWEAVE_SAFETY_BLANKY(213, "Codweave Safety Blanky", PouchCategory.TEXTILES, Rarity.COMMON, PouchEffect.fromId(213), 120),
    SILKEN_STOOL(214, "Silken Stool", PouchCategory.TEXTILES, Rarity.RARE, PouchEffect.fromId(214), 120),
    NOPONCHO(215, "Noponcho", PouchCategory.TEXTILES, Rarity.RARE, PouchEffect.fromId(215), 144),
    PRISMATIC_HEADBAND(216, "Prismatic Headband", PouchCategory.TEXTILES, Rarity.LEGENDARY, PouchEffect.fromId(216), 192),
    FONDANT_RICE_CAKE(217, "Fondant Rice Cake", PouchCategory.STAPLE_FOODS, Rarity.COMMON, PouchEffect.fromId(217), 20),
    TANTALESE_PORRIDGE(218, "Tantalese Porridge", PouchCategory.STAPLE_FOODS, Rarity.COMMON, PouchEffect.fromId(218), 20),
    POACHED_FRUIT_SAMOD(219, "Poached Fruit Samod", PouchCategory.STAPLE_FOODS, Rarity.RARE, PouchEffect.fromId(219), 30),
    GRUMBIRD_RICE_BOWL(220, "Grumbird Rice Bowl", PouchCategory.STAPLE_FOODS, Rarity.LEGENDARY, PouchEffect.fromId(220), 60),
    STEAMED_VEG_STRALU(221, "Steamed Veg Stralu", PouchCategory.VEGETABLES, Rarity.COMMON, PouchEffect.fromId(221), 20),
    ADDAMS_EMBERCAKES(222, "Addam's Embercakes", PouchCategory.VEGETABLES, Rarity.COMMON, PouchEffect.fromId(222), 20),
    VINAIGRETTE_ICE_CABBAGE(223, "Vinaigrette Ice Cabbage", PouchCategory.VEGETABLES, Rarity.RARE, PouchEffect.fromId(223), 40),
    PRICKLY_SNOWPICKLE(224, "Prickly Snowpickle", PouchCategory.VEGETABLES, Rarity.LEGENDARY, PouchEffect.fromId(224), 70),
    AROMALOCARIS_SAUTE(225, "Aromalocaris Sauté", PouchCategory.SEAFOOD, Rarity.COMMON, PouchEffect.fromId(225), 20),
    ABYSSTURGEON_MEDALLION(226, "Abyssturgeon Medallion", PouchCategory.SEAFOOD, Rarity.COMMON, PouchEffect.fromId(226), 20),
    BAGNA_OYSTER_ROLL(227, "Bagna Oyster Roll", PouchCategory.SEAFOOD, Rarity.RARE, PouchEffect.fromId(227), 30),
    WHITEBAIT_SAMOD_HOTPOT(228, "Whitebait-Samod Hotpot", PouchCategory.SEAFOOD, Rarity.LEGENDARY, PouchEffect.fromId(228), 50),
    AIRY_SNOWFLAKE_SHERBET(229, "Airy Snowflake Sherbet", PouchCategory.DESSERTS, Rarity.COMMON, PouchEffect.fromId(229), 20),
    THAWING_MILLE_FEUILLE(230, "Thawing Mille-Feuille", PouchCategory.DESSERTS, Rarity.COMMON, PouchEffect.fromId(230), 20),
    BAKED_NARCIPEAR(231, "Baked Narcipear", PouchCategory.DESSERTS, Rarity.COMMON, PouchEffect.fromId(231), 20),
    SNO_BAKE_CHEESECAKE(232, "Sno-Bake Cheesecake", PouchCategory.DESSERTS, Rarity.RARE, PouchEffect.fromId(232), 20),
    ODIFA_PUNCH(233, "Odifa Punch", PouchCategory.DESSERTS, Rarity.RARE, PouchEffect.fromId(233), 40),
    SNOW_DUMPLINGS(234, "Snow Dumplings", PouchCategory.DESSERTS, Rarity.LEGENDARY, PouchEffect.fromId(234), 60),
    ANCIENT_KINGS_PORTRAIT(235, "Ancient King’s Portrait", PouchCategory.ART, Rarity.LEGENDARY, PouchEffect.fromId(235), 120),
    SNOW_CRYSTAL_VASE(236, "Snow-Crystal Vase", PouchCategory.ART, Rarity.LEGENDARY, PouchEffect.fromId(236), 120),
    PORTRAIT_OF_GER_THE_HERO(237, "Portrait of Ger the Hero", PouchCategory.ART, Rarity.LEGENDARY, PouchEffect.fromId(237), 120),
    PRIDEFUL_WALKING(238, "Prideful Walking", PouchCategory.LITERATURE, Rarity.COMMON, PouchEffect.fromId(238), 120),
    THE_ARMU_WHO_LOVED(239, "The Armu Who Loved", PouchCategory.LITERATURE, Rarity.COMMON, PouchEffect.fromId(239), 120),
    WITNESS_THE_CRUSTIP(240, "Witness the Crustip", PouchCategory.LITERATURE, Rarity.COMMON, PouchEffect.fromId(240), 120),
    THE_ANNALS_OF_ADDAM(241, "The Annals of Addam", PouchCategory.LITERATURE, Rarity.RARE, PouchEffect.fromId(241), 120),
    THE_BLIZZARD_CHOIR(242, "The Blizzard Choir", PouchCategory.LITERATURE, Rarity.RARE, PouchEffect.fromId(242), 168),
    ASTROLOGY_MADE_SIMPLE(243, "Astrology Made Simple", PouchCategory.LITERATURE, Rarity.LEGENDARY, PouchEffect.fromId(243), 240),
    DON_T_FEED_THE_ARMU(244, "Don't Feed the Armu", PouchCategory.BOARD_GAMES, Rarity.COMMON, PouchEffect.fromId(244), 120),
    BLUFF_KNIGHT(245, "Bluff Knight", PouchCategory.BOARD_GAMES, Rarity.COMMON, PouchEffect.fromId(245), 120),
    MONEY_BYE_BYE(246, "Money-Bye-Bye", PouchCategory.BOARD_GAMES, Rarity.COMMON, PouchEffect.fromId(246), 120),
    SMACK_A_NOPON(247, "Smack-A-Nopon", PouchCategory.BOARD_GAMES, Rarity.RARE, PouchEffect.fromId(247), 144),
    JEWELED_BILLIARD_BALLS(248, "Jeweled Billiard Balls", PouchCategory.BOARD_GAMES, Rarity.LEGENDARY, PouchEffect.fromId(248), 192),
    STEAMY_OIL(249, "Steamy Oil", PouchCategory.COSMETICS, Rarity.COMMON, PouchEffect.fromId(249), 120),
    CHOCOLATE_SHADOW(250, "Chocolate Shadow", PouchCategory.COSMETICS, Rarity.COMMON, PouchEffect.fromId(250), 120),
    MOONSTAR_LIPSTICK(251, "Moonstar Lipstick", PouchCategory.COSMETICS, Rarity.COMMON, PouchEffect.fromId(251), 120),
    NOPONIC_NAILS(252, "Noponic Nails", PouchCategory.COSMETICS, Rarity.RARE, PouchEffect.fromId(252), 144),
    STEAM_POWDER(253, "Steam Powder", PouchCategory.COSMETICS, Rarity.LEGENDARY, PouchEffect.fromId(253), 216),
    TANTALESE_VELVET(254, "Tantalese Velvet", PouchCategory.TEXTILES, Rarity.COMMON, PouchEffect.fromId(254), 120),
    SNOWFLAKE_WEAVE_SOLE(255, "Snowflake-Weave Sole", PouchCategory.TEXTILES, Rarity.COMMON, PouchEffect.fromId(255), 120),
    GENBU_WEAVE_CLOTH(256, "Genbu-Weave Cloth", PouchCategory.TEXTILES, Rarity.COMMON, PouchEffect.fromId(256), 120),
    HEATSTRIPE(257, "Heatstripe", PouchCategory.TEXTILES, Rarity.RARE, PouchEffect.fromId(257), 120),
    MUSICAL_HAIR_CLASP(258, "Musical Hair Clasp", PouchCategory.TEXTILES, Rarity.RARE, PouchEffect.fromId(258), 192),
    TORIGOTH_SNOWPOUCH(259, "Torigoth Snowpouch", PouchCategory.TEXTILES, Rarity.LEGENDARY, PouchEffect.fromId(259), 240),
    GLITTERBAKE(260, "Glitterbake", PouchCategory.STAPLE_FOODS, Rarity.COMMON, PouchEffect.fromId(260), 20),
    TRICOLOR_BOWL(261, "Tricolor Bowl", PouchCategory.STAPLE_FOODS, Rarity.RARE, PouchEffect.fromId(261), 30),
    HOT_MOONBEAM_SALAD(262, "Hot Moonbeam Salad", PouchCategory.VEGETABLES, Rarity.COMMON, PouchEffect.fromId(262), 20),
    ADDAMS_SUPERCAKES(263, "Addam's Supercakes", PouchCategory.VEGETABLES, Rarity.RARE, PouchEffect.fromId(263), 40),
    MEATBALL_POT_AU_FEU(264, "Meatball Pot-au-Feu", PouchCategory.MEAT, Rarity.COMMON, PouchEffect.fromId(264), 20),
    PAN_FRIED_TARTARI(265, "Pan-Fried Tartari", PouchCategory.MEAT, Rarity.RARE, PouchEffect.fromId(265), 50),
    ROAST_MEAT_TAGLIATA(266, "Roast Meat Tagliata", PouchCategory.MEAT, Rarity.RARE, PouchEffect.fromId(266), 60),
    SUNSHINE_PIE(267, "Sunshine Pie", PouchCategory.MEAT, Rarity.LEGENDARY, PouchEffect.fromId(267), 70),
    ACQUA_PEARL_PAZZA(268, "Acqua Pearl Pazza", PouchCategory.MEAT, Rarity.LEGENDARY, PouchEffect.fromId(268), 20),
    VESSS_DUMPLINGS(269, "Vess’s Dumplings", PouchCategory.STAPLE_FOODS, Rarity.COMMON, PouchEffect.fromId(269), 20),
    RAINBOW_DUMPLINGS(270, "Rainbow Dumplings", PouchCategory.STAPLE_FOODS, Rarity.COMMON, PouchEffect.fromId(270), 30),
    GROMRICE_DUMPLINGS(271, "Gromrice Dumplings", PouchCategory.STAPLE_FOODS, Rarity.RARE, PouchEffect.fromId(271), 40),
    PURI_LEAF_DUMPLINGS(272, "Puri Leaf Dumplings", PouchCategory.STAPLE_FOODS, Rarity.RARE, PouchEffect.fromId(272), 50),
    SPICY_STRALU(273, "Spicy Stralu", PouchCategory.MEAT, Rarity.LEGENDARY, PouchEffect.fromId(273), 20),
    LOVEMERRY_CAKE(278, "Lovemerry Cake", PouchCategory.DESSERTS, Rarity.LEGENDARY, PouchEffect.fromId(278), 70),
    NEON_COOKIES(281, "Neon Cookies", PouchCategory.DESSERTS, Rarity.RARE, PouchEffect.fromId(281), 60),
    BITTER_CHOCLIT(283, "Bitter Choclit", PouchCategory.DESSERTS, Rarity.COMMON, PouchEffect.fromId(283), 20),
    BITLIP_DRINK(286, "Bitlip Drink", PouchCategory.DRINKS, Rarity.COMMON, PouchEffect.fromId(286), 20),
    PUCKLIP_DRINK(287, "Pucklip Drink", PouchCategory.DRINKS, Rarity.COMMON, PouchEffect.fromId(287), 20),
    TINGLIP_DRINK(288, "Tinglip Drink", PouchCategory.DRINKS, Rarity.COMMON, PouchEffect.fromId(288), 20),
    SOURLIP_DRINK(289, "Sourlip Drink", PouchCategory.DRINKS, Rarity.COMMON, PouchEffect.fromId(289), 20),
    TRICOLOR_ICE_FLOE(290, "Tricolor Ice Floe", PouchCategory.ART, Rarity.COMMON, PouchEffect.fromId(290), 144),
    SPARKLING_SNOWGLOBE(291, "Sparkling Snowglobe", PouchCategory.ART, Rarity.RARE, PouchEffect.fromId(291), 168),
    RAINBOW_SCOPE(292, "Rainbow Scope", PouchCategory.ART, Rarity.RARE, PouchEffect.fromId(292), 168),
    TANTAL_ICECUBE(293, "Tantal Icecube", PouchCategory.ART, Rarity.RARE, PouchEffect.fromId(293), 192),
    TITAN_ILLUMINATIONS(294, "Titan Illuminations", PouchCategory.ART, Rarity.LEGENDARY, PouchEffect.fromId(294), 192),
    SALTED_BROG_SAUTE(295, "Salted Brog Sauté", PouchCategory.MEAT, Rarity.RARE, PouchEffect.fromId(295), 40),
    CREAM_ORANGE_PARATHA(296, "Cream Orange Paratha", PouchCategory.STAPLE_FOODS, Rarity.RARE, PouchEffect.fromId(296), 20),
    THE_FLORA_OF_ALREST(297, "The Flora of Alrest", PouchCategory.LITERATURE, Rarity.COMMON, PouchEffect.fromId(297), 120),
    GENTLEMEN_A_STUDY(298, "Gentlemen: A Study", PouchCategory.LITERATURE, Rarity.LEGENDARY, PouchEffect.fromId(298), 120),
    QUOTELETTA(299, "Quoteletta", PouchCategory.MEAT, Rarity.RARE, PouchEffect.fromId(299), 20),
    FRIED_OCTOMAYO(301, "Fried Octomayo", PouchCategory.STAPLE_FOODS, Rarity.RARE, PouchEffect.fromId(301), 20),
    ARDAINIAN_BEAR_CARVING(302, "Ardainian Bear Carving", PouchCategory.ART, Rarity.RARE, PouchEffect.fromId(302), 120),
    MASTERS_CURRY(303, "Master's Curry", PouchCategory.STAPLE_FOODS, Rarity.RARE, PouchEffect.fromId(303), 20),
    LUCKY_DAWN_BREAD(304, "Lucky Dawn Bread", PouchCategory.STAPLE_FOODS, Rarity.RARE, PouchEffect.fromId(304), 20),
    CHOCLIT_DUMPLINGS(305, "Choclit Dumplings", PouchCategory.STAPLE_FOODS, Rarity.RARE, PouchEffect.fromId(305), 60),
    HEART_COOKIES(306, "Heart Cookies", PouchCategory.DESSERTS, Rarity.RARE, PouchEffect.fromId(306), 20),
    RIZZENTE_MANTLE(307, "Rizzente Mantle", PouchCategory.TEXTILES, Rarity.COMMON, PouchEffect.fromId(307), 120),
    FELT_CUSHIONING(308, "Felt Cushioning", PouchCategory.TEXTILES, Rarity.COMMON, PouchEffect.fromId(308), 120),
    BRUT_SILK(309, "Brut Silk", PouchCategory.TEXTILES, Rarity.RARE, PouchEffect.fromId(309), 120),
    SHELTON_BROADCLOTH(310, "Shelton Broadcloth", PouchCategory.TEXTILES, Rarity.RARE, PouchEffect.fromId(310), 120),
    CRINKLY_WOOL(311, "Crinkly Wool", PouchCategory.TEXTILES, Rarity.LEGENDARY, PouchEffect.fromId(311), 120),
    PYRAS_BAKED_REDFISH(312, "Pyra's Baked Redfish", PouchCategory.SEAFOOD, Rarity.LEGENDARY, PouchEffect.fromId(312), 60),
    FABULOUSLY_FIERCE_HAT(313, "Fabulously Fierce Hat", PouchCategory.TEXTILES, Rarity.LEGENDARY, PouchEffect.fromId(313), 60),
    LOVE_SOURCE(314, "Love Source", PouchCategory.DRINKS, Rarity.LEGENDARY, PouchEffect.fromId(314), 60);

    private int id, duration;
    private String name;
    private PouchCategory category;
    private Rarity rarity;
    private PouchEffect pEffect;

    PouchItem(int id, String name, PouchCategory category, Rarity rarity, PouchEffect pEffect, int duration) {
        this.id = id+40000;
        this.duration = duration;
        this.name = name;
        this.category = category;
        this.rarity = rarity;
        this.pEffect = pEffect;
    }

    public static PouchItem fromId(short id) {
        for (PouchItem item:values()) {
            if(id == (short)(item.id & 0xFFFF))
                return item;
        }
        return null;
    }

    public static PouchItem fromName(String name) {
        for (PouchItem item:values()) {
            if(name.equalsIgnoreCase(item.name))
                return item;
        }
        return null;
    }

    public static String[] stringValues() {
        ArrayList<String> strValues = new ArrayList<>();
        for(PouchItem item:values()) {
            strValues.add(item.getName());
        }
        return strValues.toArray(new String[0]);
    }

    public int getId() {
        return id;
    }

    public int getDuration() {
        return duration;
    }

    public String getName() {
        return name;
    }

    public PouchCategory getCategory() {
        return category;
    }

    public Rarity getRarity() {
        return rarity;
    }

    public PouchEffect getPouchEffect() {
        return pEffect;
    }
}
