package me.notanullpointer.xc2editor.save.structure;

import me.notanullpointer.xc2editor.save.parser.Int16;
import me.notanullpointer.xc2editor.save.parser.Int32;
import me.notanullpointer.xc2editor.save.parser.Int8;
import me.notanullpointer.xc2editor.save.parser.String16;

public class SDataBlade {

    public Int16 dataType;
    public Int16 creator;
    public Int16 setDriver;
    public Int16 bladeId;
    public Int32 bornTime;
    public SDataIdea ideaData;
    public Int32 field_2C;
    public Int8 field_30;
    public Int8 gap31[/*3*/];
    public Int32 trustPoints;
    public Int32 trustRank;
    public SDataBladeArts bArts[/*3*/];
    public SDataBladeArtsN nArts[/*3*/];
    public SDataBladeArtsEx bArtsEx[/*2*/];
    public SDataBladeSkill bladeSkills[/*3*/];
    public SDataBladeSkill fieldSkill[/*3*/];
    public Int8 extraParts2[/*4*/];
    public AchievInfo bArtsAchieve[/*3*/];
    public AchievInfo bSkillsAchieve[/*3*/];
    public AchievInfo fSKillsAchieve[/*3*/];
    public AchievInfo keyAchievement;
    public Int16 keyReleaseLevel;
    public FavoriteData favorites[/*2*/];
    public Int16 gap676;
    public Int16 equipOrbs[/*3*/];
    public Int16 gap67E;
    public Int32 equipOrbHandles[/*3*/];
    public EquipHana hanaEquip;
    public Int8 race;
    public Int8 gender;
    public Int16 still;
    public String16 modelResourceName;
    public String16 model2Name;
    public String16 motionResourceName;
    public String16 motion2Name;
    public String16 addMotionName;
    public String16 voiceName;
    public String16 clipEvent;
    public String16 com_SE;
    public String16 effectResourceName;
    public String16 com_VO;
    public String16 centerBone;
    public String16 camBone;
    public String16 seResourceName;
    public Int8 bladeSize;
    public Int8 weaponType;
    public Int8 orbNum;
    public Int8 atr;
    public Int8 personality;
    public Int8 extraParts;
    public Int8 eyeRot;
    public Int8 gap_827;
    public Int16 coolTime;
    public Int16 condition;
    public Int16 defWeapon;
    public Int16 chestHeight;
    public Int16 landingHeight;
    public Int16 rareNameId;
    public Int16 commonNameId;
    public Int16 scale;
    public Int16 wpnScale;
    public Int16 offsetId;
    public Int16 collisionId;
    public Int8 pArmor;
    public Int8 eArmor;
    public Int8 hpMaxRev;
    public Int8 strengthRev;
    public Int8 powEtherRev;
    public Int8 dexRev;
    public Int8 agilityRev;
    public Int8 luckRev;
    public Int8 questRace;
    public Int8 releaseLock;
    public Int8 footStep;
    public Int8 footStepEffect;
    public Int16 kitzunaLinkSet;
    public Int16 normalTalk;
    public Int16 gap_84E;
    public Int32 createEventId;
    public Int16 mountPoint;
    public Int16 mountObject;
    public Int8 name[/*64*/];
    public Int32 nameLength;
    public Int16 commonBladeIndex;
    public Int8 enableEngageRex;
    public Int8 bladeReleaseStatus;
    public Int8 isUnselect;
    public Int8 affinityChartStatus;
    public Int16 field_8A2;


}
